# 코드 실습에 앞서 머신러닝, 딥러닝에 대해 학습

## 예: 지도학습, 비지도학습, 군집화, 신경망 개념, 손실 함수, 최적화(경사하강법, 역전파, 학습률), 최적화 알고리즘(SGD, Adam)

## 텐서란?
### 텐서는 numpy에 존재하는데 배열, 행렬과 유사한 자료 구조 

In [1]:
import torch

print(torch.tensor([1, 2, 3])) # 입력 데이터 형식을 참조해 해당 자료형 텐서를생성, 입력 데이터 복사해서 생성
print(torch.Tensor([[1, 2, 3],[4, 5, 6]])) # 자동으로 float 형식의 텐서 생성, # 텐서 인스턴스 생성
print(torch.LongTensor([1, 2, 3])) # Long 자료형 텐서
print(torch.FloatTensor([1, 2, 3])) # float형 자료형 텐서 

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


In [2]:
import torch


tensor = torch.rand(1, 2)
print(tensor) 
print(tensor.shape) # 텐서 차원 출력
print(tensor.dtype) # 텐서 타입 출력
print(tensor.device) # 텐서의 저장 위치

tensor([[0.9081, 0.7480]])
torch.Size([1, 2])
torch.float32
cpu


In [3]:
import torch

tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape)
tensor = tensor.reshape(2, 1) #차원 변환 # view()도 존재한다.
print(tensor)
print(tensor.shape)

tensor([[0.0529, 0.3562]])
torch.Size([1, 2])
tensor([[0.0529],
        [0.3562]])
torch.Size([2, 1])


In [4]:
import torch


tensor = torch.rand((3, 3), dtype=torch.float) # 자료형 설정 방법
print(tensor)

tensor([[0.3186, 0.6584, 0.0475],
        [0.2441, 0.4476, 0.7344],
        [0.1849, 0.3153, 0.3337]])


In [5]:
import torch


device = "cuda" if torch.cuda.is_available() else "cpu" 
cpu = torch.FloatTensor([1, 2, 3])
gpu = torch.cuda.FloatTensor([1, 2, 3])
tensor = torch.rand((1, 1), device=device) # 텐서의 저장 위치 설정
print(device)
print(cpu)
print(gpu)
print(tensor)

cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.0758]], device='cuda:0')


C:\Users\user\AppData\Local\Temp\ipykernel_40620\721341711.py:6: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ..\torch\csrc\tensor\python_tensor.cpp:85.)
  gpu = torch.cuda.FloatTensor([1, 2, 3])


In [6]:
# 애플 실리콘이 탑재된 맥 사용자의 경우
import torch


device = "mps" if torch.backends.mps.is_available() and torch.backends.mps.is_built() else "cpu"
cpu = torch.FloatTensor([1, 2, 3])
mps = torch.rand((1, 1), device=device)
print(device)
print(mps)

cpu
tensor([[0.5972]])


In [7]:
import torch


cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.cuda() # gpu()로 변경
gpu2cpu = gpu.cpu() # Cpu()로 변경
cpu2gpu = cpu.to("cuda") # to('장치')로도 가능
print(cpu)
print(gpu)
print(gpu2cpu)
print(cpu2gpu)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


In [8]:
import torch
import numpy as np

"""
numpy 배열을 파이토치 텐서로
"""
ndarray = np.array([1, 2, 3], dtype=np.uint8) 
print(torch.tensor(ndarray)) 
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


In [9]:
import torch

"""
detach()는 파이토치 텐서의 경우 모든 연산을 추적하여 역전파 연산등에 사용됨으로 
연산 그래프에서 제거하기 위해 사용해야함
"""
tensor = torch.cuda.FloatTensor([1, 2, 3])
ndarray = tensor.detach().cpu().numpy() #파이토치 텐서 자료형을 numpy 배열로
print(ndarray)
print(type(ndarray))

import torch


#tensor = torch.FloatTensor([1, 2, 3]).to("mps") #mac 에서는 주석 해제 해서 실행
ndarray = tensor.detach().cpu().numpy() 
print(ndarray)
print(type(ndarray))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1. 2. 3.]
<class 'numpy.ndarray'>


## 단순 선형 회귀 구현
### Numpy

In [10]:
import numpy as np
# 입력
x = np.array(
    [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]]
) 
# 정답
y = np.array(
    [[0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]]
)

In [11]:
weight = 0.0 # 초기 가중치 
bias = 0.0 # 초기 bias
learning_rate = 0.005 # 학습률

In [12]:
for epoch in range(10000): #epoch 학습 횟수
    y_hat = weight * x + bias # 정답 예측 선형 회귀 이므로 y=wx+b

    cost = ((y - y_hat) ** 2).mean() # 오차 측정 mse 

    weight = weight - learning_rate * ((y_hat - y) * x).mean() # 가중치 조절
    bias = bias - learning_rate * (y_hat - y).mean() # bias 조절

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Weight : {weight:.3f}, Bias : {bias:.3f}, Cost : {cost:.3f}")

Epoch : 1000, Weight : 0.872, Bias : -0.290, Cost : 1.377
Epoch : 2000, Weight : 0.877, Bias : -0.391, Cost : 1.373
Epoch : 3000, Weight : 0.878, Bias : -0.422, Cost : 1.372
Epoch : 4000, Weight : 0.879, Bias : -0.432, Cost : 1.372
Epoch : 5000, Weight : 0.879, Bias : -0.435, Cost : 1.372
Epoch : 6000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 7000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 8000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.436, Cost : 1.372


### Pytorch 선형 회귀

In [13]:
from torch import optim

In [14]:
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

In [15]:
weight = torch.zeros(1, requires_grad=True)
bias = torch.zeros(1, requires_grad=True)
learning_rate = 0.001

In [16]:
optimizer = optim.SGD([weight, bias], lr=learning_rate) # SGD 옵티마이저 사용

In [17]:
for epoch in range(10000):
    hypothesis = weight * x + bias
    cost = torch.mean((hypothesis - y) ** 2)

    optimizer.zero_grad() # 이전 gradients 값을 0으로 설정, 텐서의 기울기는 grad 속성에 누적되어 더해지기 때문에, 
    cost.backward() # loss 역전파
    optimizer.step() # #최적화 함수에 계산된 가중치와 편향들을 반영

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Weight : {weight.item():.3f}, Bias : {bias.item():.3f}, Cost : {cost:.3f}")

Epoch : 1000, Weight : 0.864, Bias : -0.138, Cost : 1.393
Epoch : 2000, Weight : 0.870, Bias : -0.251, Cost : 1.380
Epoch : 3000, Weight : 0.873, Bias : -0.321, Cost : 1.375
Epoch : 4000, Weight : 0.875, Bias : -0.364, Cost : 1.373
Epoch : 5000, Weight : 0.877, Bias : -0.391, Cost : 1.373
Epoch : 6000, Weight : 0.878, Bias : -0.408, Cost : 1.372
Epoch : 7000, Weight : 0.878, Bias : -0.419, Cost : 1.372
Epoch : 8000, Weight : 0.878, Bias : -0.425, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.429, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.432, Cost : 1.372


In [18]:
import torch
from torch import optim


x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

weight = torch.zeros(1, requires_grad=True)
bias = torch.zeros(1, requires_grad=True)
learning_rate = 0.001

optimizer = optim.SGD([weight, bias], lr=learning_rate)

for epoch in range(10000):
    hypothesis = weight * x + bias
    cost = torch.mean((hypothesis - y) ** 2)
    
    print(f"Epoch : {epoch+1:4d}")
    print(f"Step [1] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")

    optimizer.zero_grad()
    print(f"Step [2] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")

    cost.backward()
    print(f"Step [3] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")

    optimizer.step()
    print(f"Step [4] : Gradient : {weight.grad}, Weight : {weight.item():.5f}")
    
    if epoch == 3:
        break

Epoch :    1
Step [1] : Gradient : None, Weight : 0.00000
Step [2] : Gradient : None, Weight : 0.00000
Step [3] : Gradient : tensor([-540.4854]), Weight : 0.00000
Step [4] : Gradient : tensor([-540.4854]), Weight : 0.54049
Epoch :    2
Step [1] : Gradient : tensor([-540.4854]), Weight : 0.54049
Step [2] : Gradient : None, Weight : 0.54049
Step [3] : Gradient : tensor([-198.9818]), Weight : 0.54049
Step [4] : Gradient : tensor([-198.9818]), Weight : 0.73947
Epoch :    3
Step [1] : Gradient : tensor([-198.9818]), Weight : 0.73947
Step [2] : Gradient : None, Weight : 0.73947
Step [3] : Gradient : tensor([-73.2604]), Weight : 0.73947
Step [4] : Gradient : tensor([-73.2604]), Weight : 0.81273
Epoch :    4
Step [1] : Gradient : tensor([-73.2604]), Weight : 0.81273
Step [2] : Gradient : None, Weight : 0.81273
Step [3] : Gradient : tensor([-26.9772]), Weight : 0.81273
Step [4] : Gradient : tensor([-26.9772]), Weight : 0.83970


### torch.nn 신경망 패키지 사용

In [19]:
import torch
from torch import nn
from torch import optim

In [20]:
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

In [21]:
# torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)
"""
in_features: 신경망의 입력 뉴런 수
out_features: 신경망의 출력 뉴런수
"""
layer=nn.Linear(1, 1, bias=True, device=None, dtype=None)
layer

Linear(in_features=1, out_features=1, bias=True)

In [22]:
model = nn.Linear(1, 1)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [23]:
for epoch in range(10000):
    output = model(x)
    cost = criterion(output, y)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.8702]], requires_grad=True), Parameter containing:
tensor([-0.2588], requires_grad=True)], Cost : 1.380
Epoch : 2000, Model : [Parameter containing:
tensor([[0.8735]], requires_grad=True), Parameter containing:
tensor([-0.3257], requires_grad=True)], Cost : 1.375
Epoch : 3000, Model : [Parameter containing:
tensor([[0.8755]], requires_grad=True), Parameter containing:
tensor([-0.3673], requires_grad=True)], Cost : 1.373
Epoch : 4000, Model : [Parameter containing:
tensor([[0.8768]], requires_grad=True), Parameter containing:
tensor([-0.3933], requires_grad=True)], Cost : 1.373
Epoch : 5000, Model : [Parameter containing:
tensor([[0.8776]], requires_grad=True), Parameter containing:
tensor([-0.4094], requires_grad=True)], Cost : 1.372
Epoch : 6000, Model : [Parameter containing:
tensor([[0.8781]], requires_grad=True), Parameter containing:
tensor([-0.4194], requires_grad=True)], Cost : 1.372
Epoch : 7000, Model : [Parameter contain

## 데이터세트, 데이터 로더

### 데이터셋은 특정 입력데이터와 정답지를 제공해주기 위해 제공하는 클래스
### 데이터로더는 데이터세트에 저장된 데이터를 어떠한 방식으로 불러와 활용하지는 정의

In [72]:
from torch.utils.data import Dataset, DataLoader, random_split
import pandas as pd

In [63]:
class CustomDataset(Dataset):
    def __init__(self, data_path):
        """
            입력 데이터의 전처리 과정 수행 메소드
            학습에 필요한 데이터 형태로 변형하는 과정
        """
        self.data = pd.read_csv(data_path)
        
       
        self.X = self.data.iloc[:, 1:-1].values  
        self.y = self.data.iloc[:, -1].values  

        self.label_map = {label: idx for idx, label in enumerate(sorted(set(self.y)))}
        self.y = [self.label_map[label] for label in self.y]

    def __len__(self):
        """
            데이터 전체 개수 반환
        """
        return len(self.data)
    
    def __getitem__(self, idx):
        """
            학습이 진행 될 때, 하나의 데이터 샘플을 반환하는 메소드
        """
        x = torch.tensor(self.X[idx], dtype=torch.float32)
        y = torch.tensor(self.y[idx], dtype=torch.long)
        return x, y


In [66]:
dataset = CustomDataset('Iris.csv')
dataloader = DataLoader(dataset, batch_size=2, shuffle=True, num_workers=0, drop_last=False) 
# drop_last: 배치 단위로 데이터를 가져오는 경우 배치보다 작은 경우 존재한다. 이 때, True면 배치 크기보다 작으면 가져오지 않는다

In [71]:
dataset[0]

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))

In [70]:
next(iter(dataloader))

[tensor([[7.3000, 2.9000, 6.3000, 1.8000],
         [7.9000, 3.8000, 6.4000, 2.0000],
         [4.8000, 3.4000, 1.9000, 0.2000],
         [6.8000, 2.8000, 4.8000, 1.4000]]),
 tensor([2, 2, 0, 1])]

In [82]:

dataset_size = len(dataset)
train_size = int(dataset_size * 0.7)
validation_size = int(dataset_size * 0.15)
test_size = dataset_size - train_size - validation_size

train_dataset, validation_dataset, test_dataset = random_split(dataset, [train_size, validation_size, test_size]) # 데이터셋 분리
print(f"Training Data Size : {len(train_dataset)}")
print(f"Validation Data Size : {len(validation_dataset)}")
print(f"Testing Data Size : {len(test_dataset)}")

train_dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True, drop_last=True)
validation_dataloader = DataLoader(validation_dataset, batch_size=4, shuffle=True, drop_last=True)
test_dataloader = DataLoader(test_dataset, batch_size=4, shuffle=True, drop_last=True)

Training Data Size : 105
Validation Data Size : 22
Testing Data Size : 23


## 모델 구현
### nn.Module 상속 받아 서브클래스로 제작

In [91]:
import torch.nn.functional as F

In [122]:
class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()
        """
            모델 레이어 선언
        """
        self.layer1 = nn.Linear(4, 4)
        self.layer2 = nn.Linear(4, 3)
    def forward(self, x):
        """
            순전파 과정 작성
        """
        out = F.relu(self.layer1(x))
        out = F.relu(self.layer2(out))
        
        return out
        

In [124]:
model = CustomModel().to(device)
optimizer = optim.SGD(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

## iris dataset train and model save

### 모델 저장 방법은 torch.save(model, path), 불러오는 방법 torch.load(path, map_location) map_location: 모델 장치 설정 

### 중요한점은 model 인스턴스를 저장 할 때, 모델 전체를 저장 할 수 도 있고, 모델 상태만 저장 가능

In [125]:
for epoch in range(10000):
    train_loss = 0
    val_loss = 0
    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)
        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
    for x, y in validation_dataloader:
        x = x.to(device)
        y = y.to(device)
        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        val_loss += loss.item()
    
    print(f'{epoch}, train_loss: {train_loss/len(train_dataloader)}, val_loss: {val_loss/len(validation_dataloader)}')
       

0, train_loss: 1.0970689058303833, val_loss: 1.1208529949188233
1, train_loss: 1.0964369361217206, val_loss: 1.144818162918091
2, train_loss: 1.0926966735949883, val_loss: 1.0866971015930176
3, train_loss: 1.0899724524754744, val_loss: 1.126435399055481
4, train_loss: 1.0946032519523914, val_loss: 1.1120399236679077
5, train_loss: 1.0940483625118549, val_loss: 1.095466959476471
6, train_loss: 1.0906881873424237, val_loss: 1.1235671520233155
7, train_loss: 1.088030111331206, val_loss: 1.1226458311080934
8, train_loss: 1.086980938911438, val_loss: 1.1076229810714722
9, train_loss: 1.0924096015783458, val_loss: 1.12067391872406
10, train_loss: 1.0868570827520811, val_loss: 1.0908809542655944
11, train_loss: 1.0867642783201659, val_loss: 1.0914372205734253
12, train_loss: 1.0863305101027856, val_loss: 1.1200945854187012
13, train_loss: 1.0909379835312183, val_loss: 1.1174624919891358
14, train_loss: 1.0854188272586236, val_loss: 1.0883784532546996
15, train_loss: 1.0846409522570097, val_lo

133, train_loss: 1.074704484297679, val_loss: 1.0692167043685914
134, train_loss: 1.0712237472717578, val_loss: 1.0684911489486695
135, train_loss: 1.0750095156522899, val_loss: 1.0665980100631713
136, train_loss: 1.0745398769011865, val_loss: 1.047727108001709
137, train_loss: 1.0749351909527411, val_loss: 1.063467538356781
138, train_loss: 1.0748280814060798, val_loss: 1.044848084449768
139, train_loss: 1.0708649112628057, val_loss: 1.0468290090560912
140, train_loss: 1.074684787255067, val_loss: 1.0666366457939147
141, train_loss: 1.0747948907888853, val_loss: 1.0658403754234314
142, train_loss: 1.0745175618391771, val_loss: 1.0639983534812927
143, train_loss: 1.0744654627946706, val_loss: 1.0660336017608643
144, train_loss: 1.0735501738694997, val_loss: 1.0618476510047912
145, train_loss: 1.0743083839233105, val_loss: 1.0260773420333862
146, train_loss: 1.070622613796821, val_loss: 1.0254459142684937
147, train_loss: 1.07378024321336, val_loss: 1.061331284046173
148, train_loss: 1.

265, train_loss: 1.06462339254526, val_loss: 1.030836319923401
266, train_loss: 1.0610712927121382, val_loss: 1.0285249471664428
267, train_loss: 1.065127581357956, val_loss: 1.0455490589141845
268, train_loss: 1.0643320633814886, val_loss: 1.0450671792030335
269, train_loss: 1.0607281304322755, val_loss: 1.0258431434631348
270, train_loss: 1.0642430851092706, val_loss: 1.0258256554603578
271, train_loss: 1.064009625178117, val_loss: 1.0490086078643799
272, train_loss: 1.060555806526771, val_loss: 1.027996826171875
273, train_loss: 1.0649529695510864, val_loss: 1.0057157754898072
274, train_loss: 1.0603259526766264, val_loss: 1.0234151244163514
275, train_loss: 1.063694036923922, val_loss: 1.0443276643753052
276, train_loss: 1.0599890970266783, val_loss: 1.025149655342102
277, train_loss: 1.0638133241580083, val_loss: 1.0237481594085693
278, train_loss: 1.0599540770053864, val_loss: 1.0229647517204286
279, train_loss: 1.063552384193127, val_loss: 1.024044644832611
280, train_loss: 1.05

394, train_loss: 1.0503597809718206, val_loss: 1.007102632522583
395, train_loss: 1.0470328330993652, val_loss: 1.0250148177146912
396, train_loss: 1.050133622609652, val_loss: 0.9904473781585693
397, train_loss: 1.0501064199667711, val_loss: 1.0232597589492798
398, train_loss: 1.0499469477396746, val_loss: 1.0288962721824646
399, train_loss: 1.0467208692660699, val_loss: 1.0260076880455018
400, train_loss: 1.0504874197336345, val_loss: 1.003869080543518
401, train_loss: 1.0496044434033907, val_loss: 1.0073952674865723
402, train_loss: 1.0459284140513494, val_loss: 1.0283995747566224
403, train_loss: 1.0500590686614697, val_loss: 1.0256159424781799
404, train_loss: 1.0490489441614885, val_loss: 1.0278268933296204
405, train_loss: 1.0496612328749437, val_loss: 1.0074254989624023
406, train_loss: 1.0460185775390038, val_loss: 1.0025999665260314
407, train_loss: 1.0494046807289124, val_loss: 1.0072341680526733
408, train_loss: 1.0485616899453676, val_loss: 1.0277634978294372
409, train_lo

524, train_loss: 1.0299253440820253, val_loss: 1.0069980025291443
525, train_loss: 1.0297509065041175, val_loss: 1.0045935750007629
526, train_loss: 1.0265552126444304, val_loss: 1.0110839486122132
527, train_loss: 1.0303335052270155, val_loss: 1.0089480400085449
528, train_loss: 1.0296304432245402, val_loss: 0.9913602709770203
529, train_loss: 1.0302438690112188, val_loss: 1.0070276618003846
530, train_loss: 1.0287285309571486, val_loss: 1.0031612396240235
531, train_loss: 1.0292937893133898, val_loss: 0.9859187006950378
532, train_loss: 1.0283800822037916, val_loss: 0.9933483719825744
533, train_loss: 1.0294877015627348, val_loss: 0.9836754918098449
534, train_loss: 1.0289685336443095, val_loss: 1.0005114316940307
535, train_loss: 1.0277900925049415, val_loss: 1.002284300327301
536, train_loss: 1.0284719260839315, val_loss: 0.9909204244613647
537, train_loss: 1.0286233608539288, val_loss: 0.9837003827095032
538, train_loss: 1.0279611440805287, val_loss: 0.9873885989189148
539, train_

651, train_loss: 1.0025996772142558, val_loss: 0.9774925112724304
652, train_loss: 1.0005698502063751, val_loss: 0.973811936378479
653, train_loss: 1.0002764532199273, val_loss: 0.9604787826538086
654, train_loss: 1.0000312832685618, val_loss: 0.9767881751060485
655, train_loss: 1.0005797445774078, val_loss: 0.9580682992935181
656, train_loss: 1.000123686515368, val_loss: 0.9604374408721924
657, train_loss: 0.9991355171570411, val_loss: 0.982883095741272
658, train_loss: 0.9988649510420285, val_loss: 0.9774632096290589
659, train_loss: 0.9985524943241706, val_loss: 0.9750048875808716
660, train_loss: 0.9954534814907954, val_loss: 0.9671562314033508
661, train_loss: 0.9980106949806213, val_loss: 0.9766224503517151
662, train_loss: 0.9977025527220506, val_loss: 0.9665326118469239
663, train_loss: 0.9943582369731023, val_loss: 0.9593841552734375
664, train_loss: 0.9940822720527649, val_loss: 0.9574065804481506
665, train_loss: 0.9944042082016284, val_loss: 0.9543638467788697
666, train_lo

782, train_loss: 0.9585556594225076, val_loss: 0.9392747282981873
783, train_loss: 0.95922029706148, val_loss: 0.929268765449524
784, train_loss: 0.9557471940150628, val_loss: 0.9386910438537598
785, train_loss: 0.9555220764416915, val_loss: 0.9067089676856994
786, train_loss: 0.9582878557535318, val_loss: 0.9398625612258911
787, train_loss: 0.9589550311748798, val_loss: 0.9237895846366883
788, train_loss: 0.9546039677583255, val_loss: 0.9118585467338562
789, train_loss: 0.9569660539810474, val_loss: 0.9459577798843384
790, train_loss: 0.9568592722599323, val_loss: 0.9342744588851929
791, train_loss: 0.9556915462017059, val_loss: 0.9337334394454956
792, train_loss: 0.9534737995037665, val_loss: 0.9158557891845703
793, train_loss: 0.9557042213586661, val_loss: 0.9170266389846802
794, train_loss: 0.9547974673601297, val_loss: 0.9193159103393554
795, train_loss: 0.9544483446157895, val_loss: 0.9233400702476502
796, train_loss: 0.9554916551479926, val_loss: 0.9277462601661682
797, train_lo

913, train_loss: 0.9196188128911532, val_loss: 0.8917195558547973
914, train_loss: 0.9208895976726825, val_loss: 0.9031549096107483
915, train_loss: 0.9190924580280597, val_loss: 0.8802514791488647
916, train_loss: 0.9222993300511286, val_loss: 0.8970582604408264
917, train_loss: 0.9201018214225769, val_loss: 0.8635424971580505
918, train_loss: 0.9214347348763392, val_loss: 0.892333447933197
919, train_loss: 0.9217081276270059, val_loss: 0.8915746092796326
920, train_loss: 0.9192071167322305, val_loss: 0.898888111114502
921, train_loss: 0.9173656495717856, val_loss: 0.8821076989173889
922, train_loss: 0.9187741485925821, val_loss: 0.8845871090888977
923, train_loss: 0.9167189987806174, val_loss: 0.8880637288093567
924, train_loss: 0.9165017054631159, val_loss: 0.880084216594696
925, train_loss: 0.9155804537809812, val_loss: 0.8608506202697754
926, train_loss: 0.9199101283000066, val_loss: 0.887021791934967
927, train_loss: 0.9156642831288851, val_loss: 0.8891791343688965
928, train_los

1039, train_loss: 0.8905010383862716, val_loss: 0.8268477320671082
1040, train_loss: 0.8899123233098251, val_loss: 0.8322584986686706
1041, train_loss: 0.8877251079449286, val_loss: 0.8584004044532776
1042, train_loss: 0.8873191200769864, val_loss: 0.8434186339378357
1043, train_loss: 0.8903416693210602, val_loss: 0.8697062969207764
1044, train_loss: 0.8889957139125237, val_loss: 0.8656029105186462
1045, train_loss: 0.8866935899624457, val_loss: 0.8485628008842468
1046, train_loss: 0.8862833472398611, val_loss: 0.8676131129264831
1047, train_loss: 0.8860588532227737, val_loss: 0.8305451154708863
1048, train_loss: 0.8877580005388993, val_loss: 0.833618414402008
1049, train_loss: 0.8874861827263465, val_loss: 0.833731186389923
1050, train_loss: 0.8873905745836405, val_loss: 0.8524215698242188
1051, train_loss: 0.8832229971885681, val_loss: 0.8433195352554321
1052, train_loss: 0.8832749678538396, val_loss: 0.8637366652488708
1053, train_loss: 0.8861809120728419, val_loss: 0.82211793661117

1168, train_loss: 0.8544202309388381, val_loss: 0.7937962532043457
1169, train_loss: 0.855141804768489, val_loss: 0.8145133495330811
1170, train_loss: 0.8580698737731347, val_loss: 0.8326186299324035
1171, train_loss: 0.8578015221999242, val_loss: 0.8383652210235596
1172, train_loss: 0.854361375937095, val_loss: 0.8315580606460571
1173, train_loss: 0.8564846492730654, val_loss: 0.8186366200447083
1174, train_loss: 0.852991562623244, val_loss: 0.8313896298408509
1175, train_loss: 0.8525589544039506, val_loss: 0.8088957905769348
1176, train_loss: 0.8522803898041065, val_loss: 0.8137254118919373
1177, train_loss: 0.8529086112976074, val_loss: 0.819084620475769
1178, train_loss: 0.8548433069999402, val_loss: 0.8007587790489197
1179, train_loss: 0.852621351297085, val_loss: 0.8006803631782532
1180, train_loss: 0.8523739759738629, val_loss: 0.8119074106216431
1181, train_loss: 0.8506954885446109, val_loss: 0.8161742448806762
1182, train_loss: 0.8539145703499134, val_loss: 0.8275006890296936


1291, train_loss: 0.8264371913212997, val_loss: 0.795210886001587
1292, train_loss: 0.8253774963892423, val_loss: 0.7950787901878357
1293, train_loss: 0.826091142801138, val_loss: 0.7908931255340577
1294, train_loss: 0.8258463098452642, val_loss: 0.8020636796951294
1295, train_loss: 0.825710823902717, val_loss: 0.791742205619812
1296, train_loss: 0.827814920590474, val_loss: 0.7924271583557129
1297, train_loss: 0.8273314100045425, val_loss: 0.8061963200569153
1298, train_loss: 0.8280373032276447, val_loss: 0.7883030533790588
1299, train_loss: 0.8281268729613378, val_loss: 0.7938746452331543
1300, train_loss: 0.8245944862182324, val_loss: 0.7991401553153992
1301, train_loss: 0.8230523329514724, val_loss: 0.800524091720581
1302, train_loss: 0.8242455377028539, val_loss: 0.7774638652801513
1303, train_loss: 0.8228509265642899, val_loss: 0.7905763626098633
1304, train_loss: 0.8228903344044318, val_loss: 0.7825852394104004
1305, train_loss: 0.8263668922277597, val_loss: 0.7823326110839843
1

1422, train_loss: 0.8009357635791485, val_loss: 0.7777764916419982
1423, train_loss: 0.8034077951541314, val_loss: 0.757467246055603
1424, train_loss: 0.8010007991240575, val_loss: 0.7595279932022094
1425, train_loss: 0.8008470810376681, val_loss: 0.7657070517539978
1426, train_loss: 0.8011586803656358, val_loss: 0.7792518138885498
1427, train_loss: 0.8002946216326493, val_loss: 0.7693926334381104
1428, train_loss: 0.8003182823841388, val_loss: 0.7538410902023316
1429, train_loss: 0.8024413058390985, val_loss: 0.7788029313087463
1430, train_loss: 0.799942101423557, val_loss: 0.7582949519157409
1431, train_loss: 0.7993733814129462, val_loss: 0.7768931984901428
1432, train_loss: 0.8000097206005683, val_loss: 0.769995927810669
1433, train_loss: 0.7998955456110147, val_loss: 0.7795377612113953
1434, train_loss: 0.7992450090555044, val_loss: 0.7779651403427124
1435, train_loss: 0.7994782397380242, val_loss: 0.7538399577140809
1436, train_loss: 0.8024276540829585, val_loss: 0.752648711204528

1546, train_loss: 0.7809776228207809, val_loss: 0.7447516322135925
1547, train_loss: 0.7805904539731833, val_loss: 0.7389465689659118
1548, train_loss: 0.780295158808048, val_loss: 0.7504401564598083
1549, train_loss: 0.7804923882851234, val_loss: 0.7500771045684814
1550, train_loss: 0.7799597863967602, val_loss: 0.7499563694000244
1551, train_loss: 0.7801685929298401, val_loss: 0.7476150274276734
1552, train_loss: 0.782444532100971, val_loss: 0.7672320485115052
1553, train_loss: 0.779531866312027, val_loss: 0.7466433882713318
1554, train_loss: 0.779319201524441, val_loss: 0.7496979713439942
1555, train_loss: 0.7787241362608396, val_loss: 0.7578823566436768
1556, train_loss: 0.7792061773630289, val_loss: 0.7494479298591614
1557, train_loss: 0.7807984535510724, val_loss: 0.746100389957428
1558, train_loss: 0.778958607178468, val_loss: 0.7303309321403504
1559, train_loss: 0.7787170249682206, val_loss: 0.7452054262161255
1560, train_loss: 0.7780360946288476, val_loss: 0.7535595655441284
1

1676, train_loss: 0.7610074602640592, val_loss: 0.7377497673034668
1677, train_loss: 0.7609862822752732, val_loss: 0.7175687074661254
1678, train_loss: 0.7609392931828132, val_loss: 0.7302608251571655
1679, train_loss: 0.7607094874748817, val_loss: 0.7166801333427429
1680, train_loss: 0.7606161420161908, val_loss: 0.7196713089942932
1681, train_loss: 0.7624512268946722, val_loss: 0.7438713431358337
1682, train_loss: 0.7601594833227304, val_loss: 0.7321866512298584
1683, train_loss: 0.7602187738968775, val_loss: 0.7284170508384704
1684, train_loss: 0.7625423142543206, val_loss: 0.7299580216407776
1685, train_loss: 0.7621583984448359, val_loss: 0.7193740010261536
1686, train_loss: 0.759721054480626, val_loss: 0.7266281485557556
1687, train_loss: 0.76188525557518, val_loss: 0.7449180960655213
1688, train_loss: 0.7594171647842114, val_loss: 0.7371510028839111
1689, train_loss: 0.7592995327252609, val_loss: 0.7313937067985534
1690, train_loss: 0.7590636610984802, val_loss: 0.729441249370575

1808, train_loss: 0.7441818232719715, val_loss: 0.7147838473320007
1809, train_loss: 0.7450597011126004, val_loss: 0.702906358242035
1810, train_loss: 0.7443385009582226, val_loss: 0.7010120749473572
1811, train_loss: 0.74252283343902, val_loss: 0.7025320649147033
1812, train_loss: 0.7444298152740185, val_loss: 0.7033552169799805
1813, train_loss: 0.742425799369812, val_loss: 0.7177360892295838
1814, train_loss: 0.7419065947716053, val_loss: 0.701585841178894
1815, train_loss: 0.7421887654524583, val_loss: 0.7026633381843567
1816, train_loss: 0.7417923922722156, val_loss: 0.7122023940086365
1817, train_loss: 0.7414167981881362, val_loss: 0.7168095350265503
1818, train_loss: 0.7435086507063645, val_loss: 0.7017958760261536
1819, train_loss: 0.7416868141064277, val_loss: 0.7123894214630127
1820, train_loss: 0.7413379206107213, val_loss: 0.712082040309906
1821, train_loss: 0.7414520245331985, val_loss: 0.7092817425727844
1822, train_loss: 0.7407223467643445, val_loss: 0.7162022471427918
1

1939, train_loss: 0.726663921888058, val_loss: 0.6993145823478699
1940, train_loss: 0.7261586372668927, val_loss: 0.6991786122322082
1941, train_loss: 0.7264315463029422, val_loss: 0.6888317704200745
1942, train_loss: 0.7263298424390646, val_loss: 0.6968986749649048
1943, train_loss: 0.7262118756771088, val_loss: 0.6985309004783631
1944, train_loss: 0.7255915793088766, val_loss: 0.6943281650543213
1945, train_loss: 0.7254248972122486, val_loss: 0.6954685330390931
1946, train_loss: 0.7254261420323298, val_loss: 0.705202579498291
1947, train_loss: 0.7271486131044534, val_loss: 0.6880630850791931
1948, train_loss: 0.7251432698506576, val_loss: 0.6964576482772827
1949, train_loss: 0.7255242329377395, val_loss: 0.6973559856414795
1950, train_loss: 0.7253850927719703, val_loss: 0.6984996438026428
1951, train_loss: 0.7252512207398047, val_loss: 0.6964159131050109
1952, train_loss: 0.7263680008741525, val_loss: 0.7001759886741639
1953, train_loss: 0.7244969079127679, val_loss: 0.70813295841217

2066, train_loss: 0.7118124938928164, val_loss: 0.6882482528686523
2067, train_loss: 0.7128523932053492, val_loss: 0.6728369355201721
2068, train_loss: 0.710967079951213, val_loss: 0.6762141227722168
2069, train_loss: 0.7126475297487699, val_loss: 0.6823283433914185
2070, train_loss: 0.7113487307841961, val_loss: 0.6849806189537049
2071, train_loss: 0.7105533366019909, val_loss: 0.683383560180664
2072, train_loss: 0.7128704648751479, val_loss: 0.6836721897125244
2073, train_loss: 0.7102236747741699, val_loss: 0.6801321268081665
2074, train_loss: 0.7102921077838311, val_loss: 0.685454273223877
2075, train_loss: 0.7103566458592048, val_loss: 0.6720413208007813
2076, train_loss: 0.7100170804904058, val_loss: 0.6836230039596558
2077, train_loss: 0.7105540839525369, val_loss: 0.6817385911941528
2078, train_loss: 0.7113883747504308, val_loss: 0.6826247930526733
2079, train_loss: 0.7103475125936362, val_loss: 0.6920970320701599
2080, train_loss: 0.7102187367585989, val_loss: 0.671886658668518

2192, train_loss: 0.6973320429141705, val_loss: 0.6833219289779663
2193, train_loss: 0.697252638064898, val_loss: 0.6662058234214783
2194, train_loss: 0.6973606967009031, val_loss: 0.6602661490440369
2195, train_loss: 0.6968238032781161, val_loss: 0.6662031173706054
2196, train_loss: 0.6971422021205609, val_loss: 0.6716322541236878
2197, train_loss: 0.6976632865575644, val_loss: 0.6743599057197571
2198, train_loss: 0.6988456638959738, val_loss: 0.6678492426872253
2199, train_loss: 0.6970537602901459, val_loss: 0.6677324295043945
2200, train_loss: 0.6973614211265857, val_loss: 0.6681267499923706
2201, train_loss: 0.696430327800604, val_loss: 0.657560658454895
2202, train_loss: 0.6971990901690263, val_loss: 0.6751006841659546
2203, train_loss: 0.6962282772247608, val_loss: 0.6585816621780396
2204, train_loss: 0.6969877275136801, val_loss: 0.6677165508270264
2205, train_loss: 0.6959184729135953, val_loss: 0.6766165614128112
2206, train_loss: 0.6966792895243719, val_loss: 0.662383508682250

2327, train_loss: 0.6829356917968163, val_loss: 0.653759777545929
2328, train_loss: 0.6835059523582458, val_loss: 0.6617749333381653
2329, train_loss: 0.6846784101082728, val_loss: 0.656128191947937
2330, train_loss: 0.6848901877036462, val_loss: 0.6602184653282166
2331, train_loss: 0.6832378369111282, val_loss: 0.6657687067985535
2332, train_loss: 0.6853426992893219, val_loss: 0.6598090171813965
2333, train_loss: 0.684124054817053, val_loss: 0.6526298761367798
2334, train_loss: 0.6844859742201291, val_loss: 0.6659539341926575
2335, train_loss: 0.682191190811304, val_loss: 0.6631330490112305
2336, train_loss: 0.682725571669065, val_loss: 0.6651087403297424
2337, train_loss: 0.6826859277028304, val_loss: 0.6516713976860047
2338, train_loss: 0.6836266265465663, val_loss: 0.6715660929679871
2339, train_loss: 0.6835472927643702, val_loss: 0.6621246933937073
2340, train_loss: 0.6823742366754092, val_loss: 0.661568558216095
2341, train_loss: 0.6822578586064852, val_loss: 0.6655732989311218
2

2460, train_loss: 0.6720565282381498, val_loss: 0.6411229372024536
2461, train_loss: 0.6708786923151749, val_loss: 0.6409164428710937
2462, train_loss: 0.6725840889490567, val_loss: 0.642624294757843
2463, train_loss: 0.670369606751662, val_loss: 0.6507640361785889
2464, train_loss: 0.671902562563236, val_loss: 0.6502778887748718
2465, train_loss: 0.6722529232501984, val_loss: 0.6559381604194641
2466, train_loss: 0.6717094710239997, val_loss: 0.6380199551582336
2467, train_loss: 0.6726469420469724, val_loss: 0.6494951367378234
2468, train_loss: 0.6715676326018113, val_loss: 0.6553103208541871
2469, train_loss: 0.6722264542029455, val_loss: 0.6499465823173523
2470, train_loss: 0.671333773778035, val_loss: 0.6526564478874206
2471, train_loss: 0.6712862826310672, val_loss: 0.6351151823997497
2472, train_loss: 0.6711972287068, val_loss: 0.6554339289665222
2473, train_loss: 0.6695422988671523, val_loss: 0.6332636713981629
2474, train_loss: 0.6720104676026565, val_loss: 0.6437593698501587
24

2592, train_loss: 0.6609956667973444, val_loss: 0.6300724267959594
2593, train_loss: 0.659236864401744, val_loss: 0.6451852679252624
2594, train_loss: 0.6612167793970841, val_loss: 0.6247947692871094
2595, train_loss: 0.660771016891186, val_loss: 0.6248958230018615
2596, train_loss: 0.6609438909934118, val_loss: 0.6343778967857361
2597, train_loss: 0.6591158302930685, val_loss: 0.6312082052230835
2598, train_loss: 0.660022898362233, val_loss: 0.6423009753227233
2599, train_loss: 0.6589636137852302, val_loss: 0.6318392872810363
2600, train_loss: 0.6603581125919635, val_loss: 0.6457253456115722
2601, train_loss: 0.6584877303013434, val_loss: 0.6423930644989013
2602, train_loss: 0.6603701412677765, val_loss: 0.6329899787902832
2603, train_loss: 0.6607508705212519, val_loss: 0.6408947825431823
2604, train_loss: 0.6610309825493739, val_loss: 0.6453558564186096
2605, train_loss: 0.6605179951741145, val_loss: 0.6345741868019104
2606, train_loss: 0.6580625497377836, val_loss: 0.639064157009124

2723, train_loss: 0.6485150800301478, val_loss: 0.6336251258850097
2724, train_loss: 0.6501800486674676, val_loss: 0.6333133578300476
2725, train_loss: 0.6484454365877005, val_loss: 0.633101224899292
2726, train_loss: 0.6500114087875073, val_loss: 0.6249122500419617
2727, train_loss: 0.6482018759617438, val_loss: 0.6322574615478516
2728, train_loss: 0.648125593478863, val_loss: 0.635520589351654
2729, train_loss: 0.6497747439604539, val_loss: 0.6264370322227478
2730, train_loss: 0.6506294837364783, val_loss: 0.6310620546340943
2731, train_loss: 0.6505193916650919, val_loss: 0.6318253636360168
2732, train_loss: 0.649547143624379, val_loss: 0.6353261351585389
2733, train_loss: 0.6477976212134728, val_loss: 0.6338794589042663
2734, train_loss: 0.6494705791656787, val_loss: 0.6303926944732666
2735, train_loss: 0.6492720406789046, val_loss: 0.6410328269004821
2736, train_loss: 0.6496920929505274, val_loss: 0.6139338731765747
2737, train_loss: 0.6491064704381503, val_loss: 0.6267133355140686

2848, train_loss: 0.6380956448041476, val_loss: 0.6150839328765869
2849, train_loss: 0.6406814799858973, val_loss: 0.6146562337875366
2850, train_loss: 0.6384461086529952, val_loss: 0.6139664888381958
2851, train_loss: 0.6403614328457758, val_loss: 0.6230100750923157
2852, train_loss: 0.6397828436814822, val_loss: 0.6317433834075927
2853, train_loss: 0.6401949020532461, val_loss: 0.6252780556678772
2854, train_loss: 0.6382160003368671, val_loss: 0.6210039973258972
2855, train_loss: 0.6404483249554267, val_loss: 0.6152926921844483
2856, train_loss: 0.6376481239612286, val_loss: 0.6225722551345825
2857, train_loss: 0.6402262586813706, val_loss: 0.615861976146698
2858, train_loss: 0.6397308776011834, val_loss: 0.6066856861114502
2859, train_loss: 0.6398559739956489, val_loss: 0.6260006546974182
2860, train_loss: 0.6400154737325815, val_loss: 0.6244664549827575
2861, train_loss: 0.6397068798542023, val_loss: 0.619583249092102
2862, train_loss: 0.637588232755661, val_loss: 0.624314475059509

2974, train_loss: 0.631631965820606, val_loss: 0.6157801270484924
2975, train_loss: 0.6314779886832604, val_loss: 0.6032212734222412
2976, train_loss: 0.6289770213457254, val_loss: 0.5963453531265259
2977, train_loss: 0.631453853387099, val_loss: 0.5984429597854615
2978, train_loss: 0.6290091665891501, val_loss: 0.6055078506469727
2979, train_loss: 0.6289574985320752, val_loss: 0.6157371163368225
2980, train_loss: 0.6290368965038886, val_loss: 0.6177381873130798
2981, train_loss: 0.6289913356304169, val_loss: 0.6130577802658081
2982, train_loss: 0.6289287415834574, val_loss: 0.6180767297744751
2983, train_loss: 0.6306384182893313, val_loss: 0.6088092803955079
2984, train_loss: 0.6289204336129702, val_loss: 0.6057277321815491
2985, train_loss: 0.6314784173782055, val_loss: 0.5973251461982727
2986, train_loss: 0.6286356815925012, val_loss: 0.615312111377716
2987, train_loss: 0.6282940346461076, val_loss: 0.614285159111023
2988, train_loss: 0.6283472111591926, val_loss: 0.6160500168800354

3101, train_loss: 0.6231645827109997, val_loss: 0.610492742061615
3102, train_loss: 0.6230523013151609, val_loss: 0.6011194229125977
3103, train_loss: 0.620949408182731, val_loss: 0.5897855043411255
3104, train_loss: 0.622377104484118, val_loss: 0.5970019459724426
3105, train_loss: 0.6224472110088055, val_loss: 0.6076520562171936
3106, train_loss: 0.6200879170344427, val_loss: 0.5978766798973083
3107, train_loss: 0.6203505144669459, val_loss: 0.6135515093803405
3108, train_loss: 0.6224403404272519, val_loss: 0.5972381114959717
3109, train_loss: 0.6226504215827355, val_loss: 0.6135140776634216
3110, train_loss: 0.6225367944974166, val_loss: 0.6060255169868469
3111, train_loss: 0.6198994173453405, val_loss: 0.6049753308296204
3112, train_loss: 0.6217992649628565, val_loss: 0.5957513809204101
3113, train_loss: 0.6202293932437897, val_loss: 0.601264488697052
3114, train_loss: 0.6219922991899344, val_loss: 0.6068491578102112
3115, train_loss: 0.6194265553584466, val_loss: 0.5995375633239746

3232, train_loss: 0.614831255032466, val_loss: 0.5907859086990357
3233, train_loss: 0.6143811494112015, val_loss: 0.5999549508094788
3234, train_loss: 0.6125390896430383, val_loss: 0.5865084290504455
3235, train_loss: 0.6138870395146884, val_loss: 0.5945384681224823
3236, train_loss: 0.6123150908029996, val_loss: 0.6005514025688171
3237, train_loss: 0.6149829901181735, val_loss: 0.5935739874839783
3238, train_loss: 0.6146384110817542, val_loss: 0.5900236248970032
3239, train_loss: 0.6148136693697709, val_loss: 0.5933968544006347
3240, train_loss: 0.6119041397021368, val_loss: 0.5924967646598815
3241, train_loss: 0.6142361622590286, val_loss: 0.6050990939140319
3242, train_loss: 0.6114045748343835, val_loss: 0.5820369005203248
3243, train_loss: 0.6133970664097712, val_loss: 0.5973896384239197
3244, train_loss: 0.6114566463690537, val_loss: 0.5904992341995239
3245, train_loss: 0.6117151081562042, val_loss: 0.5927931785583496
3246, train_loss: 0.6135309086396143, val_loss: 0.5868398189544

3356, train_loss: 0.6071771314510932, val_loss: 0.5783265233039856
3357, train_loss: 0.6071681769994589, val_loss: 0.5842625975608826
3358, train_loss: 0.6047144887539057, val_loss: 0.600297474861145
3359, train_loss: 0.6046384618832514, val_loss: 0.592865240573883
3360, train_loss: 0.606920219384707, val_loss: 0.5832849264144897
3361, train_loss: 0.6060051734630878, val_loss: 0.5952784299850464
3362, train_loss: 0.6068190313302554, val_loss: 0.5878047347068787
3363, train_loss: 0.6067848388965313, val_loss: 0.5829904556274415
3364, train_loss: 0.6044897024448102, val_loss: 0.5926199793815613
3365, train_loss: 0.6066908400792342, val_loss: 0.5896785616874695
3366, train_loss: 0.6041288926051214, val_loss: 0.5915903210639953
3367, train_loss: 0.6041029657308872, val_loss: 0.5953838229179382
3368, train_loss: 0.6057325349404261, val_loss: 0.5813980221748352
3369, train_loss: 0.6038414377432603, val_loss: 0.5742828369140625
3370, train_loss: 0.6038370453394376, val_loss: 0.586868536472320

3482, train_loss: 0.6001065694368802, val_loss: 0.5960353493690491
3483, train_loss: 0.6000732802427732, val_loss: 0.5746853590011597
3484, train_loss: 0.5999579165990536, val_loss: 0.5898321151733399
3485, train_loss: 0.5972119248830355, val_loss: 0.5938898503780365
3486, train_loss: 0.5998874111817434, val_loss: 0.5739524126052856
3487, train_loss: 0.5997953300292675, val_loss: 0.573905074596405
3488, train_loss: 0.5997486286438428, val_loss: 0.5851803541183471
3489, train_loss: 0.5996720550151972, val_loss: 0.5878653287887573
3490, train_loss: 0.599558215874892, val_loss: 0.5810265064239502
3491, train_loss: 0.5990439366835815, val_loss: 0.5780839562416077
3492, train_loss: 0.5965416156328641, val_loss: 0.591830050945282
3493, train_loss: 0.5971187903330877, val_loss: 0.5781388938426971
3494, train_loss: 0.5989664621078051, val_loss: 0.5723616600036621
3495, train_loss: 0.5957414679802381, val_loss: 0.5732389569282532
3496, train_loss: 0.5985245693188447, val_loss: 0.5735067486763
3

3612, train_loss: 0.5895917025896219, val_loss: 0.5846343159675598
3613, train_loss: 0.5928380512274228, val_loss: 0.5890433430671692
3614, train_loss: 0.5927854673220561, val_loss: 0.5873716354370118
3615, train_loss: 0.5900438061127296, val_loss: 0.5889758467674255
3616, train_loss: 0.5927013777769529, val_loss: 0.5689740657806397
3617, train_loss: 0.5899395552965311, val_loss: 0.5740151286125184
3618, train_loss: 0.5926228406337591, val_loss: 0.5819481790065766
3619, train_loss: 0.592545836017682, val_loss: 0.5625060677528382
3620, train_loss: 0.5925398274109914, val_loss: 0.5751654505729675
3621, train_loss: 0.5912502660201147, val_loss: 0.5826136350631714
3622, train_loss: 0.5924886350448315, val_loss: 0.5765455484390258
3623, train_loss: 0.5897318468644068, val_loss: 0.588680100440979
3624, train_loss: 0.5894591751006933, val_loss: 0.5739591598510743
3625, train_loss: 0.589452191041066, val_loss: 0.5675281763076783
3626, train_loss: 0.5892423379879731, val_loss: 0.580104482173919

3736, train_loss: 0.5834678422946197, val_loss: 0.5657595753669739
3737, train_loss: 0.585018093769367, val_loss: 0.5835347890853881
3738, train_loss: 0.5830381959676743, val_loss: 0.5640587568283081
3739, train_loss: 0.5831601252922645, val_loss: 0.5617002844810486
3740, train_loss: 0.5859156869924985, val_loss: 0.5697418451309204
3741, train_loss: 0.5861551692852607, val_loss: 0.5788312077522277
3742, train_loss: 0.5861002630912341, val_loss: 0.5771941900253296
3743, train_loss: 0.5829145747881669, val_loss: 0.561653196811676
3744, train_loss: 0.5844849072969877, val_loss: 0.5786446809768677
3745, train_loss: 0.5859236361888739, val_loss: 0.5845152854919433
3746, train_loss: 0.5859077240412052, val_loss: 0.5540391981601716
3747, train_loss: 0.5827498057713876, val_loss: 0.5686247229576111
3748, train_loss: 0.5831914463868508, val_loss: 0.5847513556480408
3749, train_loss: 0.5829839133299314, val_loss: 0.5841250419616699
3750, train_loss: 0.5857192094509418, val_loss: 0.56952644586563

3867, train_loss: 0.5767139861216912, val_loss: 0.5650018751621246
3868, train_loss: 0.5770917683839798, val_loss: 0.5627259731292724
3869, train_loss: 0.5785126181749197, val_loss: 0.5647520303726197
3870, train_loss: 0.5769353887209525, val_loss: 0.5625563502311707
3871, train_loss: 0.5799603038109266, val_loss: 0.5606549620628357
3872, train_loss: 0.5762891391148934, val_loss: 0.5629741668701171
3873, train_loss: 0.579956904053688, val_loss: 0.5782600820064545
3874, train_loss: 0.5770533566291516, val_loss: 0.5562100946903229
3875, train_loss: 0.5781308091603793, val_loss: 0.5781150579452514
3876, train_loss: 0.5763284265995026, val_loss: 0.5618448138237
3877, train_loss: 0.5797727406024933, val_loss: 0.5723315596580505
3878, train_loss: 0.578299866272853, val_loss: 0.5626889824867248
3879, train_loss: 0.5788947126040092, val_loss: 0.5569935441017151
3880, train_loss: 0.5762950583146169, val_loss: 0.5626349449157715
3881, train_loss: 0.5781568116866626, val_loss: 0.5683986186981201


3992, train_loss: 0.5712366149975703, val_loss: 0.5577612400054932
3993, train_loss: 0.5740404014404004, val_loss: 0.5421988248825074
3994, train_loss: 0.5740274076278393, val_loss: 0.5638727247714996
3995, train_loss: 0.5734324489648526, val_loss: 0.5574634313583374
3996, train_loss: 0.5723351412094556, val_loss: 0.556446498632431
3997, train_loss: 0.5725690378592565, val_loss: 0.5680541157722473
3998, train_loss: 0.5705836931100259, val_loss: 0.5563452482223511
3999, train_loss: 0.5725763784005091, val_loss: 0.5428196251392364
4000, train_loss: 0.5721231870926343, val_loss: 0.5645686745643616
4001, train_loss: 0.570428694670017, val_loss: 0.5602522969245911
4002, train_loss: 0.5736385652652154, val_loss: 0.5561754047870636
4003, train_loss: 0.5700346678495407, val_loss: 0.5637704312801362
4004, train_loss: 0.5735177363340671, val_loss: 0.559367573261261
4005, train_loss: 0.5700395898177073, val_loss: 0.5742439866065979
4006, train_loss: 0.5704476913580527, val_loss: 0.558236610889434

4123, train_loss: 0.565137491776393, val_loss: 0.5582116961479187
4124, train_loss: 0.5652135954453394, val_loss: 0.5483590960502625
4125, train_loss: 0.564680679486348, val_loss: 0.5576663374900818
4126, train_loss: 0.5641437069727824, val_loss: 0.5535151898860932
4127, train_loss: 0.5668584131277524, val_loss: 0.5610708177089692
4128, train_loss: 0.5680558486626699, val_loss: 0.557301115989685
4129, train_loss: 0.5643340062636596, val_loss: 0.5698618531227112
4130, train_loss: 0.5647513178678659, val_loss: 0.5612219214439392
4131, train_loss: 0.5644857814678779, val_loss: 0.5696839034557343
4132, train_loss: 0.5679276493879465, val_loss: 0.5586620807647705
4133, train_loss: 0.5678697973489761, val_loss: 0.5587756991386413
4134, train_loss: 0.5678075276888334, val_loss: 0.5599778890609741
4135, train_loss: 0.5658038854598999, val_loss: 0.5507515072822571
4136, train_loss: 0.5645055770874023, val_loss: 0.5406560838222504
4137, train_loss: 0.5648752531180015, val_loss: 0.553959053754806

4248, train_loss: 0.559723253433521, val_loss: 0.5496693551540375
4249, train_loss: 0.5587903903080866, val_loss: 0.5292249917984009
4250, train_loss: 0.5614459296831718, val_loss: 0.5398385465145111
4251, train_loss: 0.5591718290860836, val_loss: 0.5334914743900299
4252, train_loss: 0.5614298708163775, val_loss: 0.5507169604301453
4253, train_loss: 0.562675539117593, val_loss: 0.5399805068969726
4254, train_loss: 0.5593083191376466, val_loss: 0.5484205722808838
4255, train_loss: 0.5612660749600484, val_loss: 0.565593671798706
4256, train_loss: 0.5625739854115707, val_loss: 0.5285504877567291
4257, train_loss: 0.5625292395169919, val_loss: 0.5522873520851135
4258, train_loss: 0.5591821005711188, val_loss: 0.5562916040420532
4259, train_loss: 0.5612938667719181, val_loss: 0.5529823064804077
4260, train_loss: 0.5606724310379761, val_loss: 0.5315313279628754
4261, train_loss: 0.5612663294260318, val_loss: 0.5516211450099945
4262, train_loss: 0.5604904156464797, val_loss: 0.550439363718032

4371, train_loss: 0.5565517842769623, val_loss: 0.5467433094978332
4372, train_loss: 0.5541367943470294, val_loss: 0.561272144317627
4373, train_loss: 0.5576809209126693, val_loss: 0.5570531785488129
4374, train_loss: 0.5540682971477509, val_loss: 0.5599409222602845
4375, train_loss: 0.5556854674449334, val_loss: 0.5242950320243835
4376, train_loss: 0.5544417454646184, val_loss: 0.5443012475967407
4377, train_loss: 0.5575197545381693, val_loss: 0.5366880059242248
4378, train_loss: 0.5555852674520932, val_loss: 0.5434512078762055
4379, train_loss: 0.5538642750336573, val_loss: 0.5487181782722473
4380, train_loss: 0.5537703300897892, val_loss: 0.533043485879898
4381, train_loss: 0.5542653386409466, val_loss: 0.540952342748642
4382, train_loss: 0.5537034490933785, val_loss: 0.5405456304550171
4383, train_loss: 0.557262115753614, val_loss: 0.5445943951606751
4384, train_loss: 0.5554584665940359, val_loss: 0.5522886157035828
4385, train_loss: 0.5535983741283417, val_loss: 0.5615982413291931

4495, train_loss: 0.5527796940161631, val_loss: 0.552490496635437
4496, train_loss: 0.552796449798804, val_loss: 0.5553808987140656
4497, train_loss: 0.5527639698523742, val_loss: 0.5371273100376129
4498, train_loss: 0.5527542783663824, val_loss: 0.5397009015083313
4499, train_loss: 0.5485184800166351, val_loss: 0.5317368149757385
4500, train_loss: 0.5516725090833811, val_loss: 0.5483035743236542
4501, train_loss: 0.5488713727547572, val_loss: 0.5369976162910461
4502, train_loss: 0.5493733871441621, val_loss: 0.5482097864151001
4503, train_loss: 0.5525567485735967, val_loss: 0.534530621767044
4504, train_loss: 0.5525217537696545, val_loss: 0.5467110097408294
4505, train_loss: 0.5519135789229319, val_loss: 0.5406024932861329
4506, train_loss: 0.5506289784724896, val_loss: 0.5299242019653321
4507, train_loss: 0.5486829005754911, val_loss: 0.5232816934585571
4508, train_loss: 0.5523965163872793, val_loss: 0.539422333240509
4509, train_loss: 0.5523260946457202, val_loss: 0.5366100370883942

4620, train_loss: 0.5445707107965763, val_loss: 0.5226156413555145
4621, train_loss: 0.5433796621285952, val_loss: 0.5401949346065521
4622, train_loss: 0.547951354430272, val_loss: 0.5365962505340576
4623, train_loss: 0.5445814224389883, val_loss: 0.5532918393611908
4624, train_loss: 0.5463100087184173, val_loss: 0.5287091255187988
4625, train_loss: 0.5443245195425473, val_loss: 0.5413758158683777
4626, train_loss: 0.5468897383946639, val_loss: 0.5311283767223358
4627, train_loss: 0.5439855674138436, val_loss: 0.518567168712616
4628, train_loss: 0.5453839634473507, val_loss: 0.5254029750823974
4629, train_loss: 0.5463636230963927, val_loss: 0.5342179477214813
4630, train_loss: 0.5463431580708578, val_loss: 0.550858736038208
4631, train_loss: 0.5475535816871203, val_loss: 0.5365636706352234
4632, train_loss: 0.5475610804099303, val_loss: 0.5330003440380097
4633, train_loss: 0.5474946441558691, val_loss: 0.5300486981868744
4634, train_loss: 0.5439341148504844, val_loss: 0.547720068693161

4747, train_loss: 0.5435211681402646, val_loss: 0.5249600887298584
4748, train_loss: 0.5392542022925156, val_loss: 0.5325270175933838
4749, train_loss: 0.5434232732424369, val_loss: 0.5339905738830566
4750, train_loss: 0.5433510289742396, val_loss: 0.548772644996643
4751, train_loss: 0.5433483605201428, val_loss: 0.5173445761203765
4752, train_loss: 0.5432666884018824, val_loss: 0.5273482441902161
4753, train_loss: 0.5423420472786977, val_loss: 0.539653193950653
4754, train_loss: 0.5398835161557565, val_loss: 0.5338638365268707
4755, train_loss: 0.5393214970827103, val_loss: 0.5261309683322907
4756, train_loss: 0.5392704468507034, val_loss: 0.5217714190483094
4757, train_loss: 0.5413694588037637, val_loss: 0.5201439261436462
4758, train_loss: 0.5430402343089764, val_loss: 0.5219889223575592
4759, train_loss: 0.5388626834520927, val_loss: 0.5351593494415283
4760, train_loss: 0.5388447298453405, val_loss: 0.5272211492061615
4761, train_loss: 0.5415636851237371, val_loss: 0.51596254706382

4875, train_loss: 0.5347941919015005, val_loss: 0.51230309009552
4876, train_loss: 0.53496608711206, val_loss: 0.5351432085037231
4877, train_loss: 0.5347193869260641, val_loss: 0.5288766920566559
4878, train_loss: 0.5388019245404464, val_loss: 0.5095442533493042
4879, train_loss: 0.5387848317623138, val_loss: 0.5235491394996643
4880, train_loss: 0.538744262777842, val_loss: 0.5348463177680969
4881, train_loss: 0.5384854766038748, val_loss: 0.5233588814735413
4882, train_loss: 0.5362317470403818, val_loss: 0.5284669876098633
4883, train_loss: 0.5386470269698364, val_loss: 0.51144939661026
4884, train_loss: 0.5346755843896133, val_loss: 0.526193380355835
4885, train_loss: 0.5373724607320932, val_loss: 0.5092763185501099
4886, train_loss: 0.5371152689823737, val_loss: 0.5335035681724548
4887, train_loss: 0.534562274813652, val_loss: 0.5196698427200317
4888, train_loss: 0.5350060302477616, val_loss: 0.5387585759162903
4889, train_loss: 0.5372549994633748, val_loss: 0.5277614712715148
4890

5004, train_loss: 0.5324057099910883, val_loss: 0.5200605630874634
5005, train_loss: 0.5343823879957199, val_loss: 0.5227056860923767
5006, train_loss: 0.5332563943587817, val_loss: 0.5101342976093293
5007, train_loss: 0.5300818693179351, val_loss: 0.5147982716560364
5008, train_loss: 0.5306584032682272, val_loss: 0.5086634933948517
5009, train_loss: 0.5308265410936795, val_loss: 0.5219456195831299
5010, train_loss: 0.530696798975651, val_loss: 0.5284037888050079
5011, train_loss: 0.5324514554097102, val_loss: 0.5416624486446381
5012, train_loss: 0.5294714054236045, val_loss: 0.5220245599746705
5013, train_loss: 0.5319472356484487, val_loss: 0.5101521492004395
5014, train_loss: 0.5302189118587054, val_loss: 0.5192975759506225
5015, train_loss: 0.5341202628154021, val_loss: 0.5117821514606475
5016, train_loss: 0.5323724586230058, val_loss: 0.5096578657627105
5017, train_loss: 0.5324076081697757, val_loss: 0.5028030455112458
5018, train_loss: 0.5295800371811941, val_loss: 0.5192184984683

5137, train_loss: 0.527981257209411, val_loss: 0.5153230428695679
5138, train_loss: 0.5280548116335502, val_loss: 0.5165760695934296
5139, train_loss: 0.5299133578172097, val_loss: 0.5237535834312439
5140, train_loss: 0.5298772431336917, val_loss: 0.527666574716568
5141, train_loss: 0.5298591737563794, val_loss: 0.5209045290946961
5142, train_loss: 0.526336052096807, val_loss: 0.5076531231403351
5143, train_loss: 0.5259392250042695, val_loss: 0.5276305973529816
5144, train_loss: 0.5262662825676111, val_loss: 0.5151553213596344
5145, train_loss: 0.5259243043569418, val_loss: 0.496256023645401
5146, train_loss: 0.5297633420962554, val_loss: 0.5382480502128602
5147, train_loss: 0.5257945908949926, val_loss: 0.5232895374298095
5148, train_loss: 0.5280709793934455, val_loss: 0.503645795583725
5149, train_loss: 0.5260820927528235, val_loss: 0.5114465117454529
5150, train_loss: 0.525828446333225, val_loss: 0.5225958526134491
5151, train_loss: 0.529586720925111, val_loss: 0.5381893217563629
51

5270, train_loss: 0.5216468205818763, val_loss: 0.507933896780014
5271, train_loss: 0.5257915625205407, val_loss: 0.5074329078197479
5272, train_loss: 0.5247894995487653, val_loss: 0.5178802132606506
5273, train_loss: 0.5215883587415402, val_loss: 0.507149589061737
5274, train_loss: 0.5237985069935138, val_loss: 0.5233811736106873
5275, train_loss: 0.5244655505968974, val_loss: 0.5038304269313812
5276, train_loss: 0.5220232468384963, val_loss: 0.5186202764511109
5277, train_loss: 0.5255997066314404, val_loss: 0.5072450459003448
5278, train_loss: 0.521191234772022, val_loss: 0.5241073727607727
5279, train_loss: 0.5219632662259616, val_loss: 0.5137042880058289
5280, train_loss: 0.5254646860636197, val_loss: 0.5219619810581207
5281, train_loss: 0.523501748075852, val_loss: 0.5059834778308868
5282, train_loss: 0.5215358699743564, val_loss: 0.49173412322998045
5283, train_loss: 0.5254079286868756, val_loss: 0.4992681324481964
5284, train_loss: 0.5212076868002231, val_loss: 0.522973662614822

5393, train_loss: 0.5220327010521522, val_loss: 0.5151076197624207
5394, train_loss: 0.5219904906474627, val_loss: 0.5003930985927582
5395, train_loss: 0.519825925047581, val_loss: 0.5200275480747223
5396, train_loss: 0.5174893679527136, val_loss: 0.5151568710803985
5397, train_loss: 0.5202159629418299, val_loss: 0.5275858640670776
5398, train_loss: 0.5180759934278635, val_loss: 0.5199243009090424
5399, train_loss: 0.5217826458124014, val_loss: 0.5110345005989074
5400, train_loss: 0.5217839055336438, val_loss: 0.5118051946163178
5401, train_loss: 0.5197745114564896, val_loss: 0.4923188924789429
5402, train_loss: 0.5216783812412848, val_loss: 0.5275235295295715
5403, train_loss: 0.5179755229216355, val_loss: 0.4993411660194397
5404, train_loss: 0.519936217711522, val_loss: 0.5190094113349915
5405, train_loss: 0.5179497542289587, val_loss: 0.493805980682373
5406, train_loss: 0.517118731370339, val_loss: 0.5117355167865754
5407, train_loss: 0.5177795760906659, val_loss: 0.5186254024505615

5520, train_loss: 0.514606868991485, val_loss: 0.5107278764247895
5521, train_loss: 0.5128383716711631, val_loss: 0.4911938965320587
5522, train_loss: 0.5148583627664126, val_loss: 0.5207187533378601
5523, train_loss: 0.5181757406546519, val_loss: 0.5009605586528778
5524, train_loss: 0.5157187179877207, val_loss: 0.49969697594642637
5525, train_loss: 0.5151687115430832, val_loss: 0.5082485795021057
5526, train_loss: 0.5180015518115118, val_loss: 0.5172597289085388
5527, train_loss: 0.5179588955182296, val_loss: 0.5241377294063568
5528, train_loss: 0.5179343670606613, val_loss: 0.5156275629997253
5529, train_loss: 0.5160401486433469, val_loss: 0.5241828978061676
5530, train_loss: 0.5145276360786878, val_loss: 0.5053933322429657
5531, train_loss: 0.5160905810502859, val_loss: 0.49067515730857847
5532, train_loss: 0.5178165137767792, val_loss: 0.5074951589107514
5533, train_loss: 0.5141612749833328, val_loss: 0.5002379536628723
5534, train_loss: 0.517721814604906, val_loss: 0.508468216657

5643, train_loss: 0.5102989708001797, val_loss: 0.5018047273159028
5644, train_loss: 0.5095818249078897, val_loss: 0.49435330033302305
5645, train_loss: 0.5145753644979917, val_loss: 0.5102199971675873
5646, train_loss: 0.5145535595141925, val_loss: 0.4989787697792053
5647, train_loss: 0.510808065533638, val_loss: 0.5130714774131775
5648, train_loss: 0.5097682097783456, val_loss: 0.49018009305000304
5649, train_loss: 0.5107891192803016, val_loss: 0.5129245162010193
5650, train_loss: 0.5144351331087259, val_loss: 0.48050073981285096
5651, train_loss: 0.5108310156143628, val_loss: 0.4922034204006195
5652, train_loss: 0.5143798291683197, val_loss: 0.5126805663108825
5653, train_loss: 0.5143923048789685, val_loss: 0.49456769824028013
5654, train_loss: 0.5143519571194282, val_loss: 0.5127086639404297
5655, train_loss: 0.5107658459590032, val_loss: 0.5037254631519318
5656, train_loss: 0.5129485393945987, val_loss: 0.5119637548923492
5657, train_loss: 0.5116978792043833, val_loss: 0.497218143

5776, train_loss: 0.5108414601821166, val_loss: 0.47722246050834655
5777, train_loss: 0.5082965665138685, val_loss: 0.49779253005981444
5778, train_loss: 0.5082492874218867, val_loss: 0.5084905922412872
5779, train_loss: 0.5107425714914615, val_loss: 0.5172759473323822
5780, train_loss: 0.5107415948922818, val_loss: 0.5043205082416534
5781, train_loss: 0.5089841198462707, val_loss: 0.5009440898895263
5782, train_loss: 0.5106701598717616, val_loss: 0.5215752243995666
5783, train_loss: 0.5093383353490096, val_loss: 0.5139073610305787
5784, train_loss: 0.5069773357648116, val_loss: 0.5050992488861084
5785, train_loss: 0.5105243416932913, val_loss: 0.5015565693378449
5786, train_loss: 0.5067484252727948, val_loss: 0.5006686210632324
5787, train_loss: 0.508435165652862, val_loss: 0.501481294631958
5788, train_loss: 0.5105114315564816, val_loss: 0.4912690281867981
5789, train_loss: 0.5084550793354328, val_loss: 0.5215780556201934
5790, train_loss: 0.5090621881760083, val_loss: 0.521628618240

5908, train_loss: 0.5045909652343163, val_loss: 0.5183518767356873
5909, train_loss: 0.5028896457873858, val_loss: 0.5104643344879151
5910, train_loss: 0.5072043125446026, val_loss: 0.5057224988937378
5911, train_loss: 0.507128105713771, val_loss: 0.4940477848052979
5912, train_loss: 0.5032124542273008, val_loss: 0.4738823354244232
5913, train_loss: 0.5026703327894211, val_loss: 0.5056086659431458
5914, train_loss: 0.503278503051171, val_loss: 0.5056045591831207
5915, train_loss: 0.5056471400536023, val_loss: 0.49998719692230226
5916, train_loss: 0.5043831307154435, val_loss: 0.4983636736869812
5917, train_loss: 0.506940136735256, val_loss: 0.5043700814247132
5918, train_loss: 0.5050989653055484, val_loss: 0.47392686605453493
5919, train_loss: 0.5030404810722058, val_loss: 0.4880263149738312
5920, train_loss: 0.5033232363370749, val_loss: 0.4998329222202301
5921, train_loss: 0.5031811067691216, val_loss: 0.4974208533763885
5922, train_loss: 0.5049594262471566, val_loss: 0.4847234964370

6032, train_loss: 0.5011390619553052, val_loss: 0.4786474108695984
6033, train_loss: 0.5037881731987, val_loss: 0.4975160777568817
6034, train_loss: 0.5037926320846264, val_loss: 0.5154890775680542
6035, train_loss: 0.5037377499617063, val_loss: 0.5154220044612885
6036, train_loss: 0.5037492387569867, val_loss: 0.49829223155975344
6037, train_loss: 0.501544272670379, val_loss: 0.479536110162735
6038, train_loss: 0.49879319621966434, val_loss: 0.5153292000293732
6039, train_loss: 0.5036601321055338, val_loss: 0.48448596000671384
6040, train_loss: 0.500075020469152, val_loss: 0.4738504409790039
6041, train_loss: 0.5036224780174402, val_loss: 0.4808612525463104
6042, train_loss: 0.4992071344302251, val_loss: 0.4969426512718201
6043, train_loss: 0.5036366547529514, val_loss: 0.47800239324569704
6044, train_loss: 0.5035803845295539, val_loss: 0.48927255868911745
6045, train_loss: 0.5035598530219152, val_loss: 0.5022859573364258
6046, train_loss: 0.4985201908991887, val_loss: 0.4761582434177

6156, train_loss: 0.500524287040417, val_loss: 0.4753233253955841
6157, train_loss: 0.4967006559555347, val_loss: 0.473373943567276
6158, train_loss: 0.5005280535954696, val_loss: 0.4907418727874756
6159, train_loss: 0.5004887259923495, val_loss: 0.47878405451774597
6160, train_loss: 0.4956878274679184, val_loss: 0.48697423934936523
6161, train_loss: 0.5004330392067249, val_loss: 0.4910719871520996
6162, train_loss: 0.49568324708021605, val_loss: 0.4880707383155823
6163, train_loss: 0.500434045608227, val_loss: 0.4949779033660889
6164, train_loss: 0.5004307662065213, val_loss: 0.47049381136894225
6165, train_loss: 0.5003952223521012, val_loss: 0.5123202323913574
6166, train_loss: 0.5003997179178091, val_loss: 0.47344602942466735
6167, train_loss: 0.4964487529717959, val_loss: 0.48566409945487976
6168, train_loss: 0.5003644159206977, val_loss: 0.5120951116085053
6169, train_loss: 0.4980458216025279, val_loss: 0.500061857700348
6170, train_loss: 0.5002779421898035, val_loss: 0.4820246338

6280, train_loss: 0.4916318276753792, val_loss: 0.4924738943576813
6281, train_loss: 0.49745544676597303, val_loss: 0.4677468538284302
6282, train_loss: 0.4927530368933311, val_loss: 0.47797698974609376
6283, train_loss: 0.4973633564435519, val_loss: 0.5050006747245789
6284, train_loss: 0.4973672330379486, val_loss: 0.47556493282318113
6285, train_loss: 0.4945249018760828, val_loss: 0.4885741949081421
6286, train_loss: 0.4927847236394882, val_loss: 0.47505484223365785
6287, train_loss: 0.4972680222529631, val_loss: 0.47603908777236936
6288, train_loss: 0.49527440735927, val_loss: 0.4973957002162933
6289, train_loss: 0.492785414824119, val_loss: 0.49089027047157285
6290, train_loss: 0.49716523404304797, val_loss: 0.47792690992355347
6291, train_loss: 0.49566163695775545, val_loss: 0.46792388558387754
6292, train_loss: 0.4922107572738941, val_loss: 0.49093857407569885
6293, train_loss: 0.49392935977532315, val_loss: 0.5049145340919494
6294, train_loss: 0.4928403932314653, val_loss: 0.496

6403, train_loss: 0.49202391734490025, val_loss: 0.4925534904003143
6404, train_loss: 0.49010855761858135, val_loss: 0.4733258843421936
6405, train_loss: 0.4906180248810695, val_loss: 0.484329354763031
6406, train_loss: 0.4903083283167619, val_loss: 0.46444140672683715
6407, train_loss: 0.49032434821128845, val_loss: 0.4929215729236603
6408, train_loss: 0.4900867732671591, val_loss: 0.48881487250328065
6409, train_loss: 0.49268624301140124, val_loss: 0.4822396457195282
6410, train_loss: 0.48899455483143145, val_loss: 0.481879061460495
6411, train_loss: 0.4942021473095967, val_loss: 0.48578407168388366
6412, train_loss: 0.49414155116448033, val_loss: 0.48191174268722536
6413, train_loss: 0.4895926152284329, val_loss: 0.47538298964500425
6414, train_loss: 0.49413419228333694, val_loss: 0.46601776480674745
6415, train_loss: 0.4941156334601916, val_loss: 0.48584685325622556
6416, train_loss: 0.4901491483816734, val_loss: 0.46682912707328794
6417, train_loss: 0.49096822853271777, val_loss: 

6530, train_loss: 0.487360995549422, val_loss: 0.49054224491119386
6531, train_loss: 0.4891803344854942, val_loss: 0.4780526340007782
6532, train_loss: 0.4909806354687764, val_loss: 0.49063902497291567
6533, train_loss: 0.48778388362664443, val_loss: 0.47061802744865416
6534, train_loss: 0.4864380806684494, val_loss: 0.49127628803253176
6535, train_loss: 0.4864294437261728, val_loss: 0.48980902433395385
6536, train_loss: 0.4870879122844109, val_loss: 0.5048271954059601
6537, train_loss: 0.4862875124582878, val_loss: 0.46161659359931945
6538, train_loss: 0.4909194398384828, val_loss: 0.4909709393978119
6539, train_loss: 0.4849827667841545, val_loss: 0.471074765920639
6540, train_loss: 0.4885977873435387, val_loss: 0.48312203884124755
6541, train_loss: 0.4897190011464633, val_loss: 0.4739463686943054
6542, train_loss: 0.4870593295647548, val_loss: 0.46594190001487734
6543, train_loss: 0.4889722695717445, val_loss: 0.48601697087287904
6544, train_loss: 0.4866847705382567, val_loss: 0.4627

6653, train_loss: 0.4844970668737705, val_loss: 0.5011364221572876
6654, train_loss: 0.48821582014744097, val_loss: 0.48760515451431274
6655, train_loss: 0.4881995818935908, val_loss: 0.4875966489315033
6656, train_loss: 0.48365372992478883, val_loss: 0.5011176645755768
6657, train_loss: 0.488203417796355, val_loss: 0.4789368987083435
6658, train_loss: 0.4881772238474626, val_loss: 0.48171715140342714
6659, train_loss: 0.488133063683143, val_loss: 0.4646719813346863
6660, train_loss: 0.48349705223853773, val_loss: 0.4816857039928436
6661, train_loss: 0.4848669606905717, val_loss: 0.4961596608161926
6662, train_loss: 0.4839560859478437, val_loss: 0.46081714034080506
6663, train_loss: 0.4825598093179556, val_loss: 0.4756798207759857
6664, train_loss: 0.48802168438067806, val_loss: 0.4797447681427002
6665, train_loss: 0.48807832369437587, val_loss: 0.46417086720466616
6666, train_loss: 0.48423709777685314, val_loss: 0.4872749030590057
6667, train_loss: 0.4868095861031459, val_loss: 0.4656

6779, train_loss: 0.4824401048513559, val_loss: 0.47782249450683595
6780, train_loss: 0.48219707722847277, val_loss: 0.4772120833396912
6781, train_loss: 0.4851687126434766, val_loss: 0.49861345291137693
6782, train_loss: 0.4851024735432405, val_loss: 0.4710822761058807
6783, train_loss: 0.48281368613243103, val_loss: 0.45503856539726256
6784, train_loss: 0.48506251321389127, val_loss: 0.46401968598365784
6785, train_loss: 0.48506433688677275, val_loss: 0.4986282527446747
6786, train_loss: 0.4801051255602103, val_loss: 0.4732362747192383
6787, train_loss: 0.47898910080011076, val_loss: 0.4513594627380371
6788, train_loss: 0.48504696098657757, val_loss: 0.4755270957946777
6789, train_loss: 0.48498507187916684, val_loss: 0.45734617710113523
6790, train_loss: 0.4849785692416705, val_loss: 0.46270025968551637
6791, train_loss: 0.4811664934341724, val_loss: 0.4548371613025665
6792, train_loss: 0.4811613674347217, val_loss: 0.4755805850028992
6793, train_loss: 0.47918798144047076, val_loss: 

6901, train_loss: 0.47661511026895964, val_loss: 0.4824475109577179
6902, train_loss: 0.48241162529358494, val_loss: 0.4480014741420746
6903, train_loss: 0.47777204788648164, val_loss: 0.46530447006225584
6904, train_loss: 0.48243480691542995, val_loss: 0.4806100964546204
6905, train_loss: 0.4774239126306314, val_loss: 0.47974061965942383
6906, train_loss: 0.47624609562066883, val_loss: 0.4900858819484711
6907, train_loss: 0.48231403873516965, val_loss: 0.4541963517665863
6908, train_loss: 0.4823006752591867, val_loss: 0.46460756063461306
6909, train_loss: 0.4794575193753609, val_loss: 0.46115649938583375
6910, train_loss: 0.48109374596522403, val_loss: 0.46047422885894773
6911, train_loss: 0.4772441043303563, val_loss: 0.45444161891937257
6912, train_loss: 0.48218930054169434, val_loss: 0.4766148865222931
6913, train_loss: 0.4822145528518237, val_loss: 0.479928070306778
6914, train_loss: 0.4774584833246011, val_loss: 0.47810630202293397
6915, train_loss: 0.4775052534846159, val_loss: 

7025, train_loss: 0.47945485550623673, val_loss: 0.471498841047287
7026, train_loss: 0.4753611580683635, val_loss: 0.46061243414878844
7027, train_loss: 0.47734321424594295, val_loss: 0.4932882070541382
7028, train_loss: 0.4793429500781573, val_loss: 0.4742317259311676
7029, train_loss: 0.4750862912489818, val_loss: 0.4561259806156158
7030, train_loss: 0.4756257522564668, val_loss: 0.4577543377876282
7031, train_loss: 0.47367706780250257, val_loss: 0.4486826479434967
7032, train_loss: 0.4770952508999751, val_loss: 0.48821407556533813
7033, train_loss: 0.4762862210090344, val_loss: 0.4660800814628601
7034, train_loss: 0.4771648714175591, val_loss: 0.47221885323524476
7035, train_loss: 0.4751494928048207, val_loss: 0.4802488923072815
7036, train_loss: 0.4791372578877669, val_loss: 0.46898298859596255
7037, train_loss: 0.4756832340588936, val_loss: 0.4792559266090393
7038, train_loss: 0.4751351481446853, val_loss: 0.45929927825927735
7039, train_loss: 0.47902754293038297, val_loss: 0.4505

7152, train_loss: 0.47242713604982084, val_loss: 0.4516313672065735
7153, train_loss: 0.47253983181256515, val_loss: 0.46862993240356443
7154, train_loss: 0.47634563079247105, val_loss: 0.44789664149284364
7155, train_loss: 0.473312513759503, val_loss: 0.4761035740375519
7156, train_loss: 0.4762991896042457, val_loss: 0.4476716220378876
7157, train_loss: 0.47629282107720006, val_loss: 0.47765270471572874
7158, train_loss: 0.47318830627661485, val_loss: 0.45869527459144593
7159, train_loss: 0.4712759176125893, val_loss: 0.4705312728881836
7160, train_loss: 0.4761823576230269, val_loss: 0.4769633412361145
7161, train_loss: 0.47613858718138474, val_loss: 0.47072126865386965
7162, train_loss: 0.4727091032725114, val_loss: 0.47612289190292356
7163, train_loss: 0.47610172973229337, val_loss: 0.45853846073150634
7164, train_loss: 0.47607482282014996, val_loss: 0.45736612677574157
7165, train_loss: 0.4736415663590798, val_loss: 0.4522230863571167
7166, train_loss: 0.4718469868485744, val_loss:

7279, train_loss: 0.47011272609233856, val_loss: 0.4606368064880371
7280, train_loss: 0.47350822732998776, val_loss: 0.4536608338356018
7281, train_loss: 0.4700707220114194, val_loss: 0.46843254566192627
7282, train_loss: 0.46931372869473237, val_loss: 0.47890776991844175
7283, train_loss: 0.4688476054714276, val_loss: 0.4416287183761597
7284, train_loss: 0.4687885573277107, val_loss: 0.4696105122566223
7285, train_loss: 0.46816848791562593, val_loss: 0.44245184063911436
7286, train_loss: 0.46963909153754896, val_loss: 0.46323179006576537
7287, train_loss: 0.4686921685934067, val_loss: 0.45862168073654175
7288, train_loss: 0.46915360482839435, val_loss: 0.4563852310180664
7289, train_loss: 0.47332656727387357, val_loss: 0.4507060408592224
7290, train_loss: 0.4699080620820706, val_loss: 0.46582567095756533
7291, train_loss: 0.4732693066963783, val_loss: 0.47271197438240053
7292, train_loss: 0.4689980676540962, val_loss: 0.473384290933609
7293, train_loss: 0.4732273541964017, val_loss: 0

7405, train_loss: 0.46434684556264144, val_loss: 0.4850288569927216
7406, train_loss: 0.4664606543687674, val_loss: 0.48481133580207825
7407, train_loss: 0.4671521737025334, val_loss: 0.43862355351448057
7408, train_loss: 0.4706608263345865, val_loss: 0.4531802237033844
7409, train_loss: 0.46587213988487536, val_loss: 0.4531794905662537
7410, train_loss: 0.47055143461777615, val_loss: 0.45448832511901854
7411, train_loss: 0.4668440601000419, val_loss: 0.4706894099712372
7412, train_loss: 0.4680988857379326, val_loss: 0.46437908411026
7413, train_loss: 0.4668070994890653, val_loss: 0.48487324118614195
7414, train_loss: 0.46668920723291546, val_loss: 0.4511443555355072
7415, train_loss: 0.4683561256298652, val_loss: 0.4692735016345978
7416, train_loss: 0.4667218533846048, val_loss: 0.47180572152137756
7417, train_loss: 0.47037739765185577, val_loss: 0.46269055008888244
7418, train_loss: 0.46737655194906086, val_loss: 0.46593241691589354
7419, train_loss: 0.4657466388665713, val_loss: 0.4

7532, train_loss: 0.4632628388129748, val_loss: 0.48122445344924925
7533, train_loss: 0.4656176498303047, val_loss: 0.44774931073188784
7534, train_loss: 0.46267307377778566, val_loss: 0.45881747007369994
7535, train_loss: 0.46315551033386815, val_loss: 0.4596128582954407
7536, train_loss: 0.4631468986089413, val_loss: 0.4493892788887024
7537, train_loss: 0.4678757677857692, val_loss: 0.4623481512069702
7538, train_loss: 0.46786591754509854, val_loss: 0.46714858412742616
7539, train_loss: 0.4630722300364421, val_loss: 0.47650890946388247
7540, train_loss: 0.4625094922689291, val_loss: 0.4495743095874786
7541, train_loss: 0.4677730443385931, val_loss: 0.46817747354507444
7542, train_loss: 0.46399733825371814, val_loss: 0.4465520799160004
7543, train_loss: 0.4677290629882079, val_loss: 0.43736292719841
7544, train_loss: 0.4677074540119905, val_loss: 0.4680336654186249
7545, train_loss: 0.4646635450995885, val_loss: 0.45399101376533507
7546, train_loss: 0.4646938701088612, val_loss: 0.436

7655, train_loss: 0.46505472981012785, val_loss: 0.45351417660713195
7656, train_loss: 0.4650465805943196, val_loss: 0.4449463844299316
7657, train_loss: 0.46506546896237594, val_loss: 0.4533211052417755
7658, train_loss: 0.46112298506956834, val_loss: 0.4644702851772308
7659, train_loss: 0.46197884587141186, val_loss: 0.4356842041015625
7660, train_loss: 0.4599979187433536, val_loss: 0.4439707338809967
7661, train_loss: 0.461210205577887, val_loss: 0.47041475772857666
7662, train_loss: 0.45995644995799434, val_loss: 0.4790006518363953
7663, train_loss: 0.46500276029109955, val_loss: 0.4612181305885315
7664, train_loss: 0.46495692088053775, val_loss: 0.46470826864242554
7665, train_loss: 0.4649215340614319, val_loss: 0.45996988415718076
7666, train_loss: 0.46287010266230655, val_loss: 0.4414324343204498
7667, train_loss: 0.4648358466533514, val_loss: 0.44897831678390504
7668, train_loss: 0.4631414952186438, val_loss: 0.43228132724761964
7669, train_loss: 0.4600909329377688, val_loss: 0

7777, train_loss: 0.4598296783291377, val_loss: 0.4549179792404175
7778, train_loss: 0.46240489987226635, val_loss: 0.4618777632713318
7779, train_loss: 0.46234142092558056, val_loss: 0.4765515148639679
7780, train_loss: 0.45764869107649875, val_loss: 0.44649458527565
7781, train_loss: 0.45745538633603317, val_loss: 0.44685999751091005
7782, train_loss: 0.457667805827581, val_loss: 0.43777626752853394
7783, train_loss: 0.4575575005549651, val_loss: 0.45526644587516785
7784, train_loss: 0.4584504881730446, val_loss: 0.45863896012306216
7785, train_loss: 0.46228210570720524, val_loss: 0.45723543763160707
7786, train_loss: 0.45919738480677974, val_loss: 0.46202470660209655
7787, train_loss: 0.46221615775273395, val_loss: 0.445957225561142
7788, train_loss: 0.45838670432567596, val_loss: 0.4404232919216156
7789, train_loss: 0.4582811083931189, val_loss: 0.45864492654800415
7790, train_loss: 0.4570830332545134, val_loss: 0.46149123311042783
7791, train_loss: 0.4621166220078102, val_loss: 0.

7905, train_loss: 0.4548789606644557, val_loss: 0.4522134065628052
7906, train_loss: 0.4548552173834581, val_loss: 0.45153285264968873
7907, train_loss: 0.45486310812143177, val_loss: 0.44698238372802734
7908, train_loss: 0.45624298315781814, val_loss: 0.44241165518760683
7909, train_loss: 0.45576731058267445, val_loss: 0.4600475549697876
7910, train_loss: 0.45659076823638034, val_loss: 0.4399224042892456
7911, train_loss: 0.45551472902297974, val_loss: 0.43678706884384155
7912, train_loss: 0.45752528539070714, val_loss: 0.45319961905479433
7913, train_loss: 0.457127014031777, val_loss: 0.42969648241996766
7914, train_loss: 0.4552575567593941, val_loss: 0.468691748380661
7915, train_loss: 0.45435127787865126, val_loss: 0.4519978046417236
7916, train_loss: 0.4593975773224464, val_loss: 0.4553689181804657
7917, train_loss: 0.45942291216208386, val_loss: 0.47311737537384035
7918, train_loss: 0.45936621496310603, val_loss: 0.43624078035354613
7919, train_loss: 0.45737648468751174, val_loss

8030, train_loss: 0.45681113119308764, val_loss: 0.43318183422088624
8031, train_loss: 0.45455976403676546, val_loss: 0.43354094624519346
8032, train_loss: 0.4529030059392636, val_loss: 0.4309713542461395
8033, train_loss: 0.45285450839079344, val_loss: 0.44764848351478576
8034, train_loss: 0.4566769886475343, val_loss: 0.4370046854019165
8035, train_loss: 0.4566599027468608, val_loss: 0.4519843578338623
8036, train_loss: 0.45662785608034867, val_loss: 0.4488470196723938
8037, train_loss: 0.454435795545578, val_loss: 0.44986876249313357
8038, train_loss: 0.4518103267137821, val_loss: 0.43541865348815917
8039, train_loss: 0.45356372457284194, val_loss: 0.4497208297252655
8040, train_loss: 0.4566222383425786, val_loss: 0.4446878135204315
8041, train_loss: 0.4565951881500391, val_loss: 0.44091227650642395
8042, train_loss: 0.4527325045603972, val_loss: 0.4531368792057037
8043, train_loss: 0.4524796542066794, val_loss: 0.43262007236480715
8044, train_loss: 0.4565034262262858, val_loss: 0.4

8162, train_loss: 0.45079050614283633, val_loss: 0.43139726519584654
8163, train_loss: 0.45158327657442826, val_loss: 0.43407775163650514
8164, train_loss: 0.4537580930269681, val_loss: 0.43646873235702516
8165, train_loss: 0.4484364974957246, val_loss: 0.43195350766181945
8166, train_loss: 0.45373938175348133, val_loss: 0.43185009956359866
8167, train_loss: 0.4500689305938207, val_loss: 0.45437681674957275
8168, train_loss: 0.4493967787577556, val_loss: 0.42711824774742124
8169, train_loss: 0.4536504206749109, val_loss: 0.4481606721878052
8170, train_loss: 0.45261335602173436, val_loss: 0.4279306590557098
8171, train_loss: 0.4518420627483955, val_loss: 0.45287405848503115
8172, train_loss: 0.4485037590448673, val_loss: 0.44090609550476073
8173, train_loss: 0.45358388125896454, val_loss: 0.4685931444168091
8174, train_loss: 0.4535767974761816, val_loss: 0.4351525127887726
8175, train_loss: 0.4535316125704692, val_loss: 0.45418556332588195
8176, train_loss: 0.44875759516771024, val_loss

8289, train_loss: 0.4511457635806157, val_loss: 0.46533342599868777
8290, train_loss: 0.4460643988389235, val_loss: 0.429938805103302
8291, train_loss: 0.4511235791903276, val_loss: 0.465203857421875
8292, train_loss: 0.45112841633649975, val_loss: 0.4388319730758667
8293, train_loss: 0.44878972608309525, val_loss: 0.44565643072128297
8294, train_loss: 0.44808144294298613, val_loss: 0.4297292113304138
8295, train_loss: 0.45104613670936, val_loss: 0.4509094715118408
8296, train_loss: 0.44721710223418015, val_loss: 0.4257745683193207
8297, train_loss: 0.44475105232917345, val_loss: 0.44452768564224243
8298, train_loss: 0.44666290053954494, val_loss: 0.4470991790294647
8299, train_loss: 0.4481753460489787, val_loss: 0.43020681142807005
8300, train_loss: 0.44686691806866574, val_loss: 0.4312891781330109
8301, train_loss: 0.45088455080986023, val_loss: 0.4376980304718018
8302, train_loss: 0.4478072002530098, val_loss: 0.42930041551589965
8303, train_loss: 0.4484794965157142, val_loss: 0.431

8411, train_loss: 0.4443855606592618, val_loss: 0.4541590571403503
8412, train_loss: 0.44376572278829723, val_loss: 0.46241372227668764
8413, train_loss: 0.4461634640510266, val_loss: 0.43614016771316527
8414, train_loss: 0.44612274720118594, val_loss: 0.4229694664478302
8415, train_loss: 0.4470271101364723, val_loss: 0.4379761040210724
8416, train_loss: 0.44539689673827243, val_loss: 0.43266490697860716
8417, train_loss: 0.4461605101823807, val_loss: 0.4160196542739868
8418, train_loss: 0.4483152066285794, val_loss: 0.4469596385955811
8419, train_loss: 0.44826863820736224, val_loss: 0.41483274698257444
8420, train_loss: 0.44452603275959307, val_loss: 0.4364549696445465
8421, train_loss: 0.44655450032307553, val_loss: 0.46259811520576477
8422, train_loss: 0.4436540064903406, val_loss: 0.4324571490287781
8423, train_loss: 0.44454128123246706, val_loss: 0.44825843572616575
8424, train_loss: 0.44430941572556126, val_loss: 0.4479288339614868
8425, train_loss: 0.4481577712755937, val_loss: 

8536, train_loss: 0.4456472316613564, val_loss: 0.4185673475265503
8537, train_loss: 0.4456561901248418, val_loss: 0.4205044388771057
8538, train_loss: 0.4456678657577588, val_loss: 0.4299058437347412
8539, train_loss: 0.4456106401406802, val_loss: 0.41807950735092164
8540, train_loss: 0.44559294099991137, val_loss: 0.4191713213920593
8541, train_loss: 0.44083597568365246, val_loss: 0.4215292751789093
8542, train_loss: 0.4427084212119763, val_loss: 0.4560367584228516
8543, train_loss: 0.4431653733436878, val_loss: 0.42108324766159055
8544, train_loss: 0.4425336581010085, val_loss: 0.42429545521736145
8545, train_loss: 0.4421699557166833, val_loss: 0.4298420250415802
8546, train_loss: 0.44077945901797366, val_loss: 0.44435107707977295
8547, train_loss: 0.44408180793890584, val_loss: 0.44041610062122344
8548, train_loss: 0.44186417987713444, val_loss: 0.4458493173122406
8549, train_loss: 0.4454451094453151, val_loss: 0.4427004396915436
8550, train_loss: 0.4424395733154737, val_loss: 0.44

8663, train_loss: 0.44304004082312953, val_loss: 0.4428459882736206
8664, train_loss: 0.44299796854074186, val_loss: 0.40946866273880006
8665, train_loss: 0.4430079563305928, val_loss: 0.4208437740802765
8666, train_loss: 0.4382301637759575, val_loss: 0.43112084865570066
8667, train_loss: 0.43945661187171936, val_loss: 0.45308482050895693
8668, train_loss: 0.4406451491209177, val_loss: 0.4426473259925842
8669, train_loss: 0.4428960451712975, val_loss: 0.4363184213638306
8670, train_loss: 0.4390946185359588, val_loss: 0.4426839768886566
8671, train_loss: 0.4380598051043657, val_loss: 0.4531409740447998
8672, train_loss: 0.4428818884950418, val_loss: 0.42984049320220946
8673, train_loss: 0.43988267848124873, val_loss: 0.43455310463905333
8674, train_loss: 0.44115802015249544, val_loss: 0.43922812938690187
8675, train_loss: 0.4389569747906465, val_loss: 0.4138876795768738
8676, train_loss: 0.43989145641143507, val_loss: 0.4427740275859833
8677, train_loss: 0.439688218327669, val_loss: 0.4

8788, train_loss: 0.43829473623862636, val_loss: 0.41444469094276426
8789, train_loss: 0.4361590880614061, val_loss: 0.41556594967842103
8790, train_loss: 0.4348149379858604, val_loss: 0.418353858590126
8791, train_loss: 0.4353939455289107, val_loss: 0.433363801240921
8792, train_loss: 0.4364895041172321, val_loss: 0.4150460034608841
8793, train_loss: 0.4387890301071681, val_loss: 0.42880076766014097
8794, train_loss: 0.4356287385408695, val_loss: 0.4074845790863037
8795, train_loss: 0.43714533975491154, val_loss: 0.43644648790359497
8796, train_loss: 0.4343541063941442, val_loss: 0.43453928232192995
8797, train_loss: 0.44009909606896913, val_loss: 0.45437883734703066
8798, train_loss: 0.44006358144374996, val_loss: 0.4462962806224823
8799, train_loss: 0.4363391605707315, val_loss: 0.44620158076286315
8800, train_loss: 0.4400138132847272, val_loss: 0.4400369644165039
8801, train_loss: 0.4367920830845833, val_loss: 0.4334465801715851
8802, train_loss: 0.43665953095142657, val_loss: 0.42

8914, train_loss: 0.43372698586720687, val_loss: 0.43617154359817506
8915, train_loss: 0.4346804389586815, val_loss: 0.4310114860534668
8916, train_loss: 0.43751987929527575, val_loss: 0.4307913362979889
8917, train_loss: 0.43539546544735247, val_loss: 0.4220894753932953
8918, train_loss: 0.43336631243045515, val_loss: 0.4337338626384735
8919, train_loss: 0.437418044759677, val_loss: 0.430027163028717
8920, train_loss: 0.4374472281107536, val_loss: 0.41653830409049986
8921, train_loss: 0.4322735552604382, val_loss: 0.4306993544101715
8922, train_loss: 0.43370103664123094, val_loss: 0.43421393632888794
8923, train_loss: 0.43226658266324264, val_loss: 0.4514369904994965
8924, train_loss: 0.4339212333926788, val_loss: 0.43726696372032164
8925, train_loss: 0.4335197920982654, val_loss: 0.4358889937400818
8926, train_loss: 0.43730684427114636, val_loss: 0.4374347567558289
8927, train_loss: 0.43729584492169893, val_loss: 0.4174453318119049
8928, train_loss: 0.43323536389149153, val_loss: 0.4

9042, train_loss: 0.43105925619602203, val_loss: 0.4141059637069702
9043, train_loss: 0.43203574877518874, val_loss: 0.4265026330947876
9044, train_loss: 0.4348173863612689, val_loss: 0.4021372437477112
9045, train_loss: 0.43479790825110215, val_loss: 0.41887704730033876
9046, train_loss: 0.4309586836741521, val_loss: 0.4311780989170074
9047, train_loss: 0.4317302405834198, val_loss: 0.4274473488330841
9048, train_loss: 0.42869936101711714, val_loss: 0.42480258345603944
9049, train_loss: 0.4347349623074898, val_loss: 0.4450190246105194
9050, train_loss: 0.4307887852191925, val_loss: 0.44833210706710813
9051, train_loss: 0.4317359053171598, val_loss: 0.41202689707279205
9052, train_loss: 0.4294512787690529, val_loss: 0.4295801639556885
9053, train_loss: 0.43070829946261185, val_loss: 0.4343841433525085
9054, train_loss: 0.4298347784922673, val_loss: 0.4309972047805786
9055, train_loss: 0.4303437534433145, val_loss: 0.4448800265789032
9056, train_loss: 0.430466302885459, val_loss: 0.4271

9170, train_loss: 0.429114336004624, val_loss: 0.43340924978256223
9171, train_loss: 0.4287396680850249, val_loss: 0.4074170351028442
9172, train_loss: 0.42901377036021304, val_loss: 0.43214887380599976
9173, train_loss: 0.42974131955550265, val_loss: 0.41009093821048737
9174, train_loss: 0.4318486131154574, val_loss: 0.4250409662723541
9175, train_loss: 0.42582355783535886, val_loss: 0.43079338073730467
9176, train_loss: 0.4318572116585878, val_loss: 0.4254267454147339
9177, train_loss: 0.43186428340581745, val_loss: 0.4461001932621002
9178, train_loss: 0.4286294843141849, val_loss: 0.4258141279220581
9179, train_loss: 0.428830990424523, val_loss: 0.42890238761901855
9180, train_loss: 0.42777411811626875, val_loss: 0.4197735726833344
9181, train_loss: 0.42698457493231845, val_loss: 0.404257196187973
9182, train_loss: 0.43180595281032413, val_loss: 0.43160560131073
9183, train_loss: 0.4317810948078449, val_loss: 0.4284380316734314
9184, train_loss: 0.431724787904666, val_loss: 0.414548

9291, train_loss: 0.42651938990904736, val_loss: 0.4252758026123047
9292, train_loss: 0.42941788412057436, val_loss: 0.43555598258972167
9293, train_loss: 0.42939892640480626, val_loss: 0.42599897980690005
9294, train_loss: 0.42576833642446077, val_loss: 0.40885138511657715
9295, train_loss: 0.4294018309849959, val_loss: 0.4293254852294922
9296, train_loss: 0.42932864794364345, val_loss: 0.4431223809719086
9297, train_loss: 0.4232777047615785, val_loss: 0.43042572140693663
9298, train_loss: 0.42929734920079893, val_loss: 0.4225622177124023
9299, train_loss: 0.4257450138147061, val_loss: 0.4027047395706177
9300, train_loss: 0.42926237961420644, val_loss: 0.4292146623134613
9301, train_loss: 0.42372310620087844, val_loss: 0.4046910166740417
9302, train_loss: 0.42704814901718724, val_loss: 0.40987042188644407
9303, train_loss: 0.42514369464837587, val_loss: 0.4215593457221985
9304, train_loss: 0.4226109396952849, val_loss: 0.41760522723197935
9305, train_loss: 0.4247149613041144, val_loss

9416, train_loss: 0.42670338314313155, val_loss: 0.4238878309726715
9417, train_loss: 0.42192023534041184, val_loss: 0.4022571682929993
9418, train_loss: 0.42664637244664705, val_loss: 0.4238292634487152
9419, train_loss: 0.4266389264510228, val_loss: 0.41259989738464353
9420, train_loss: 0.4266210381801312, val_loss: 0.42547120451927184
9421, train_loss: 0.4227487238553854, val_loss: 0.40080217719078065
9422, train_loss: 0.42657982271451217, val_loss: 0.40294389128685
9423, train_loss: 0.42655473890212864, val_loss: 0.4199027240276337
9424, train_loss: 0.4224614432224861, val_loss: 0.41698487997055056
9425, train_loss: 0.423278764463388, val_loss: 0.4197618365287781
9426, train_loss: 0.4236111319982089, val_loss: 0.419939911365509
9427, train_loss: 0.4265114344083346, val_loss: 0.4059534966945648
9428, train_loss: 0.4222931368992879, val_loss: 0.4230912268161774
9429, train_loss: 0.42646819811600906, val_loss: 0.40491386950016023
9430, train_loss: 0.42281207041098523, val_loss: 0.4057

9538, train_loss: 0.42401607506550276, val_loss: 0.4047849714756012
9539, train_loss: 0.4240019539227852, val_loss: 0.4098590135574341
9540, train_loss: 0.4239666439019717, val_loss: 0.412098354101181
9541, train_loss: 0.4210257518749971, val_loss: 0.4124466896057129
9542, train_loss: 0.4209580375598027, val_loss: 0.39871516823768616
9543, train_loss: 0.41998661080232036, val_loss: 0.43541294932365415
9544, train_loss: 0.4191583807651813, val_loss: 0.4229017078876495
9545, train_loss: 0.42015179934409946, val_loss: 0.43064951300621035
9546, train_loss: 0.42094850884034085, val_loss: 0.42015387415885924
9547, train_loss: 0.42381483774918777, val_loss: 0.4062208294868469
9548, train_loss: 0.4190468409886727, val_loss: 0.40356179475784304
9549, train_loss: 0.4237873267668944, val_loss: 0.42560170888900756
9550, train_loss: 0.4237909706739279, val_loss: 0.40207119584083556
9551, train_loss: 0.4196013475839908, val_loss: 0.4306182265281677
9552, train_loss: 0.4211857198522641, val_loss: 0.3

9659, train_loss: 0.41805923214325535, val_loss: 0.41276814937591555
9660, train_loss: 0.41749381445921385, val_loss: 0.3961048603057861
9661, train_loss: 0.4173214945655603, val_loss: 0.41530507802963257
9662, train_loss: 0.416671661230234, val_loss: 0.4183735430240631
9663, train_loss: 0.419223207120712, val_loss: 0.42020665407180785
9664, train_loss: 0.41844628006219864, val_loss: 0.4151999056339264
9665, train_loss: 0.42132206433094466, val_loss: 0.4189599335193634
9666, train_loss: 0.41850519294922167, val_loss: 0.4144638180732727
9667, train_loss: 0.41787666655503786, val_loss: 0.4101219713687897
9668, train_loss: 0.4175957968601814, val_loss: 0.4216961026191711
9669, train_loss: 0.41765973888910735, val_loss: 0.3941351920366287
9670, train_loss: 0.41777320550038266, val_loss: 0.414204353094101
9671, train_loss: 0.41598803435380644, val_loss: 0.42119215726852416
9672, train_loss: 0.42117461676780993, val_loss: 0.40895277857780454
9673, train_loss: 0.4212177023291588, val_loss: 0.

9786, train_loss: 0.4162090844832934, val_loss: 0.39720349907875063
9787, train_loss: 0.41851449471253616, val_loss: 0.40327935218811034
9788, train_loss: 0.41508765117480206, val_loss: 0.4135324597358704
9789, train_loss: 0.4145811286110144, val_loss: 0.41648560762405396
9790, train_loss: 0.4185020396342644, val_loss: 0.41251835227012634
9791, train_loss: 0.4146927171028577, val_loss: 0.4072795808315277
9792, train_loss: 0.41419890981454116, val_loss: 0.4129007697105408
9793, train_loss: 0.4184993660220733, val_loss: 0.41173062920570375
9794, train_loss: 0.414939335332467, val_loss: 0.4104363977909088
9795, train_loss: 0.41495328969680345, val_loss: 0.4189138948917389
9796, train_loss: 0.41843662468286663, val_loss: 0.411615127325058
9797, train_loss: 0.4137138712864656, val_loss: 0.39884900450706484
9798, train_loss: 0.412837137396519, val_loss: 0.41744624376296996
9799, train_loss: 0.41547751082823825, val_loss: 0.4162036538124084
9800, train_loss: 0.4183600281293576, val_loss: 0.40

9915, train_loss: 0.4107331931591034, val_loss: 0.3928119122982025
9916, train_loss: 0.4123136974298037, val_loss: 0.3904542922973633
9917, train_loss: 0.4158860141268143, val_loss: 0.3982112020254135
9918, train_loss: 0.4121719610232573, val_loss: 0.4011370360851288
9919, train_loss: 0.4136640509733787, val_loss: 0.4025693893432617
9920, train_loss: 0.4118945552752568, val_loss: 0.40975362062454224
9921, train_loss: 0.4157940229544273, val_loss: 0.3946944892406464
9922, train_loss: 0.41577546527752507, val_loss: 0.40264729261398313
9923, train_loss: 0.41575488505455166, val_loss: 0.41174728870391847
9924, train_loss: 0.4120400072290347, val_loss: 0.396809446811676
9925, train_loss: 0.41572383504647475, val_loss: 0.40975645184516907
9926, train_loss: 0.4126346609913386, val_loss: 0.40975395441055296
9927, train_loss: 0.41567088892826665, val_loss: 0.41636934876441956
9928, train_loss: 0.4111183898953291, val_loss: 0.41270496547222135
9929, train_loss: 0.4156688285561708, val_loss: 0.42

In [127]:
torch.save(
    model,
    "../models/model.pt"
)

RuntimeError: Parent directory ../models does not exist.

In [ ]:
torch.save(
    model.state_dict(),
    "../models/model_state_dict.pt"
)

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
model = torch.load("../models/model.pt", map_location=device)
print(model)

In [ ]:
"""
    체크 포인트는 저장은 학습 중 오류 발생등으로 학습이 종료되었을 때, 학습을 처음부터 다시 시작하는 것이 아닌
    저장된 체크 포인트도 학습을 시작하기 위해서 저장함
"""
#torch.save(
#             {
#                 "model": "CustomModel",
#                 "epoch": epoch,
#                 "model_state_dict": model.state_dict(),
#                 "optimizer_state_dict": optimizer.state_dict(),
#                 "cost": cost,
#                 "description": f"CustomModel 체크포인트-{checkpoint}",
#             },
#             f"../models/checkpoint-{checkpoint}.pt",
#         )

In [ ]:

# checkpoint = torch.load("../models/checkpoint-6.pt")
# model.load_state_dict(checkpoint["model_state_dict"])
# optimizer.load_state_dict(checkpoint["optimizer_state_dict"])
# checkpoint_epoch = checkpoint["epoch"]
# checkpoint_description = checkpoint["description"]
# print(checkpoint_description)

In [126]:
"""
정확도 측정
"""
label_list = []
predictions_list = []
total = 0
correct = 0
for x, y in test_dataloader:
    x = x.to(device)
    y = y.to(device)
    output = model(x)
    predictions = torch.max(output, 1)[1]
    predictions_list.append(predictions)
    correct += (predictions==y).sum()
    total +=len(y)
print(correct * 100 / total)

tensor(100.)
